<?php
function ld_city_selectbox($ld_city){

?>
<select required="required" name="ld_city">
	<option value="">Выберите город</option>
	<option <?php selected( $ld_city, "1" ); ?> value="1">Москва и Московская область</option>
	<option <?php selected( $ld_city, "2" ); ?> value="2">Зеленоград</option>
	<option <?php selected( $ld_city, "3" ); ?> value="3">Москва</option>
	<option <?php selected( $ld_city, "4" ); ?> value="4">Апрелевка</option>
	<option <?php selected( $ld_city, "5" ); ?> value="5">Балашиха</option>
	<option <?php selected( $ld_city, "6" ); ?> value="6">Бронницы</option>
	<option <?php selected( $ld_city, "7" ); ?> value="7">Верея</option>
	<option <?php selected( $ld_city, "8" ); ?> value="8">Видное</option>
	<option <?php selected( $ld_city, "9" ); ?> value="9">Волоколамск</option>
	<option <?php selected( $ld_city, "10" ); ?> value="10">Воскресенск</option>
	<option <?php selected( $ld_city, "11" ); ?> value="11">Высоковск</option>
	<option <?php selected( $ld_city, "12" ); ?> value="12">Голицыно</option>
	<option <?php selected( $ld_city, "13" ); ?> value="13">Дедовск</option>
	<option <?php selected( $ld_city, "14" ); ?> value="14">Дзержинский</option>
	<option <?php selected( $ld_city, "15" ); ?> value="15">Дмитров</option>
	<option <?php selected( $ld_city, "16" ); ?> value="16">Долгопрудный</option>
	<option <?php selected( $ld_city, "17" ); ?> value="17">Домодедово</option>
	<option <?php selected( $ld_city, "18" ); ?> value="18">Дрезна</option>
	<option <?php selected( $ld_city, "19" ); ?> value="19">Дубна</option>
	<option <?php selected( $ld_city, "20" ); ?> value="20">Егорьевск</option>
	<option <?php selected( $ld_city, "21" ); ?> value="21">Железнодорожный</option>
	<option <?php selected( $ld_city, "22" ); ?> value="22">Жуковский</option>
	<option <?php selected( $ld_city, "23" ); ?> value="23">Зарайск</option>
	<option <?php selected( $ld_city, "24" ); ?> value="24">Звенигород</option>
	<option <?php selected( $ld_city, "25" ); ?> value="25">Ивантеевка</option>
	<option <?php selected( $ld_city, "26" ); ?> value="26">Истра</option>
	<option <?php selected( $ld_city, "27" ); ?> value="27">Кашира</option>
	<option <?php selected( $ld_city, "28" ); ?> value="28">Киевский</option>
	<option <?php selected( $ld_city, "29" ); ?> value="29">Климовск</option>
	<option <?php selected( $ld_city, "30" ); ?> value="30">Клин</option>
	<option <?php selected( $ld_city, "31" ); ?> value="31">Кокошкино</option>
	<option <?php selected( $ld_city, "32" ); ?> value="32">Коломна</option>
	<option <?php selected( $ld_city, "33" ); ?> value="33">Королев</option>
	<option <?php selected( $ld_city, "34" ); ?> value="34">Котельники</option>
	<option <?php selected( $ld_city, "35" ); ?> value="35">Красноармейск</option>
	<option <?php selected( $ld_city, "36" ); ?> value="36">Красногорск</option>
	<option <?php selected( $ld_city, "37" ); ?> value="37">Краснозаводск</option>
	<option <?php selected( $ld_city, "38" ); ?> value="38">Краснознаменск</option>
	<option <?php selected( $ld_city, "39" ); ?> value="39">Кубинка</option>
	<option <?php selected( $ld_city, "40" ); ?> value="40">Куровское</option>
	<option <?php selected( $ld_city, "41" ); ?> value="41">Ликино-Дулево</option>
	<option <?php selected( $ld_city, "42" ); ?> value="42">Лобня</option>
	<option <?php selected( $ld_city, "43" ); ?> value="43">Лосино-Петровский</option>
	<option <?php selected( $ld_city, "44" ); ?> value="44">Луховицы</option>
	<option <?php selected( $ld_city, "45" ); ?> value="45">Лыткарино</option>
	<option <?php selected( $ld_city, "46" ); ?> value="46">Люберцы</option>
	<option <?php selected( $ld_city, "47" ); ?> value="47">Можайск</option>
	<option <?php selected( $ld_city, "48" ); ?> value="48">Московский</option>
	<option <?php selected( $ld_city, "49" ); ?> value="49">Мытищи</option>
	<option <?php selected( $ld_city, "50" ); ?> value="50">Наро-Фоминск</option>
	<option <?php selected( $ld_city, "51" ); ?> value="51">Ногинск</option>
	<option <?php selected( $ld_city, "52" ); ?> value="52">Одинцово</option>
	<option <?php selected( $ld_city, "53" ); ?> value="53">Ожерелье</option>
	<option <?php selected( $ld_city, "54" ); ?> value="54">Озеры</option>
	<option <?php selected( $ld_city, "55" ); ?> value="55">Орехово-Зуево</option>
	<option <?php selected( $ld_city, "56" ); ?> value="56">Павловский Посад</option>
	<option <?php selected( $ld_city, "57" ); ?> value="57">Пересвет</option>
	<option <?php selected( $ld_city, "58" ); ?> value="58">Подольск</option>
	<option <?php selected( $ld_city, "59" ); ?> value="59">Протвино</option>
	<option <?php selected( $ld_city, "60" ); ?> value="60">Пушкино</option>
	<option <?php selected( $ld_city, "61" ); ?> value="61">Пущино</option>
	<option <?php selected( $ld_city, "62" ); ?> value="62">Раменское</option>
	<option <?php selected( $ld_city, "63" ); ?> value="63">Реутов</option>
	<option <?php selected( $ld_city, "64" ); ?> value="64">Рошаль</option>
	<option <?php selected( $ld_city, "65" ); ?> value="65">Руза</option>
	<option <?php selected( $ld_city, "66" ); ?> value="66">Селятино</option>
	<option <?php selected( $ld_city, "67" ); ?> value="67">Сергиев Посад</option>
	<option <?php selected( $ld_city, "68" ); ?> value="68">Серпухов</option>
	<option <?php selected( $ld_city, "69" ); ?> value="69">Солнечногорск</option>
	<option <?php selected( $ld_city, "70" ); ?> value="70">Солнечногорск-2</option>
	<option <?php selected( $ld_city, "71" ); ?> value="71">Солнечногорск-25</option>
	<option <?php selected( $ld_city, "72" ); ?> value="72">Солнечногорск-30</option>
	<option <?php selected( $ld_city, "73" ); ?> value="73">Солнечногорск-7</option>
	<option <?php selected( $ld_city, "74" ); ?> value="74">Старая Купавна</option>
	<option <?php selected( $ld_city, "75" ); ?> value="75">Ступино</option>
	<option <?php selected( $ld_city, "76" ); ?> value="76">Сходня</option>
	<option <?php selected( $ld_city, "77" ); ?> value="77">Талдом</option>
	<option <?php selected( $ld_city, "78" ); ?> value="78">Троицк</option>
	<option <?php selected( $ld_city, "79" ); ?> value="79">Фрязино</option>
	<option <?php selected( $ld_city, "80" ); ?> value="80">Химки</option>
	<option <?php selected( $ld_city, "81" ); ?> value="81">Хотьково</option>
	<option <?php selected( $ld_city, "82" ); ?> value="82">Черноголовка</option>
	<option <?php selected( $ld_city, "83" ); ?> value="83">Чехов</option>
	<option <?php selected( $ld_city, "84" ); ?> value="84">Чехов-1</option>
	<option <?php selected( $ld_city, "85" ); ?> value="85">Чехов-2</option>
	<option <?php selected( $ld_city, "86" ); ?> value="86">Чехов-3</option>
	<option <?php selected( $ld_city, "87" ); ?> value="87">Чехов-4</option>
	<option <?php selected( $ld_city, "88" ); ?> value="88">Чехов-5</option>
	<option <?php selected( $ld_city, "89" ); ?> value="89">Чехов-6</option>
	<option <?php selected( $ld_city, "90" ); ?> value="90">Чехов-7</option>
	<option <?php selected( $ld_city, "91" ); ?> value="91">Чехов-8</option>
	<option <?php selected( $ld_city, "92" ); ?> value="92">Шатура</option>
	<option <?php selected( $ld_city, "93" ); ?> value="93">Щелково</option>
	<option <?php selected( $ld_city, "94" ); ?> value="94">Щербинка</option>
	<option <?php selected( $ld_city, "95" ); ?> value="95">Электрогорск</option>
	<option <?php selected( $ld_city, "96" ); ?> value="96">Электросталь</option>
	<option <?php selected( $ld_city, "97" ); ?> value="97">Электроугли</option>
	<option <?php selected( $ld_city, "98" ); ?> value="98">Юбилейный</option>
	<option <?php selected( $ld_city, "99" ); ?> value="99">Яхрома</option>
	<option <?php selected( $ld_city, "100" ); ?> value="100">Санкт-Петербург</option>
	<option <?php selected( $ld_city, "101" ); ?> value="101">Зеленогорск</option>
	<option <?php selected( $ld_city, "102" ); ?> value="102">Колпино</option>
	<option <?php selected( $ld_city, "103" ); ?> value="103">Красное Село</option>
	<option <?php selected( $ld_city, "104" ); ?> value="104">Кронштадт</option>
	<option <?php selected( $ld_city, "105" ); ?> value="105">Ломоносов</option>
	<option <?php selected( $ld_city, "106" ); ?> value="106">Павловск</option>
	<option <?php selected( $ld_city, "107" ); ?> value="107">Петергоф</option>
	<option <?php selected( $ld_city, "108" ); ?> value="108">Пушкин</option>
	<option <?php selected( $ld_city, "109" ); ?> value="109">Санкт-Петербург</option>
	<option <?php selected( $ld_city, "110" ); ?> value="110">Сестрорецк</option>
	<option <?php selected( $ld_city, "111" ); ?> value="111">Нижегородская область</option>
	<option <?php selected( $ld_city, "112" ); ?> value="112">Арзамас</option>
	<option <?php selected( $ld_city, "113" ); ?> value="113">Балахна</option>
	<option <?php selected( $ld_city, "114" ); ?> value="114">Богородск</option>
	<option <?php selected( $ld_city, "115" ); ?> value="115">Бор</option>
	<option <?php selected( $ld_city, "116" ); ?> value="116">Ветлуга</option>
	<option <?php selected( $ld_city, "117" ); ?> value="117">Володарск</option>
	<option <?php selected( $ld_city, "118" ); ?> value="118">Ворсма</option>
	<option <?php selected( $ld_city, "119" ); ?> value="119">Выкса</option>
	<option <?php selected( $ld_city, "120" ); ?> value="120">Горбатов</option>
	<option <?php selected( $ld_city, "121" ); ?> value="121">Городец</option>
	<option <?php selected( $ld_city, "122" ); ?> value="122">Дзержинск</option>
	<option <?php selected( $ld_city, "123" ); ?> value="123">Заволжье</option>
	<option <?php selected( $ld_city, "124" ); ?> value="124">Княгинино</option>
	<option <?php selected( $ld_city, "125" ); ?> value="125">Кстово</option>
	<option <?php selected( $ld_city, "126" ); ?> value="126">Кулебаки</option>
	<option <?php selected( $ld_city, "127" ); ?> value="127">Лукоянов</option>
	<option <?php selected( $ld_city, "128" ); ?> value="128">Лысково</option>
	<option <?php selected( $ld_city, "129" ); ?> value="129">Навашино</option>
	<option <?php selected( $ld_city, "130" ); ?> value="130">Нижний Новгород</option>
	<option <?php selected( $ld_city, "131" ); ?> value="131">Павлово</option>
	<option <?php selected( $ld_city, "132" ); ?> value="132">Первомайск</option>
	<option <?php selected( $ld_city, "133" ); ?> value="133">Перевоз</option>
	<option <?php selected( $ld_city, "134" ); ?> value="134">Саров</option>
	<option <?php selected( $ld_city, "135" ); ?> value="135">Семенов</option>
	<option <?php selected( $ld_city, "136" ); ?> value="136">Сергач</option>
	<option <?php selected( $ld_city, "137" ); ?> value="137">Урень</option>
	<option <?php selected( $ld_city, "138" ); ?> value="138">Чкаловск</option>
	<option <?php selected( $ld_city, "139" ); ?> value="139">Шахунья</option>
	<option <?php selected( $ld_city, "140" ); ?> value="140">Краснодарский край</option>
	<option <?php selected( $ld_city, "141" ); ?> value="141">Абинск</option>
	<option <?php selected( $ld_city, "142" ); ?> value="142">Анапа</option>
	<option <?php selected( $ld_city, "143" ); ?> value="143">Апшеронск</option>
	<option <?php selected( $ld_city, "144" ); ?> value="144">Армавир</option>
	<option <?php selected( $ld_city, "145" ); ?> value="145">Белореченск</option>
	<option <?php selected( $ld_city, "146" ); ?> value="146">Геленджик</option>
	<option <?php selected( $ld_city, "147" ); ?> value="147">Горячий Ключ</option>
	<option <?php selected( $ld_city, "148" ); ?> value="148">Гулькевичи</option>
	<option <?php selected( $ld_city, "149" ); ?> value="149">Ейск</option>
	<option <?php selected( $ld_city, "150" ); ?> value="150">Кореновск</option>
	<option <?php selected( $ld_city, "151" ); ?> value="151">Краснодар</option>
	<option <?php selected( $ld_city, "152" ); ?> value="152">Кропоткин</option>
	<option <?php selected( $ld_city, "153" ); ?> value="153">Крымск</option>
	<option <?php selected( $ld_city, "154" ); ?> value="154">Курганинск</option>
	<option <?php selected( $ld_city, "155" ); ?> value="155">Лабинск</option>
	<option <?php selected( $ld_city, "156" ); ?> value="156">Новокубанск</option>
	<option <?php selected( $ld_city, "157" ); ?> value="157">Новороссийск</option>
	<option <?php selected( $ld_city, "158" ); ?> value="158">Приморско-Ахтарск</option>
	<option <?php selected( $ld_city, "159" ); ?> value="159">Славянск-на-Кубани</option>
	<option <?php selected( $ld_city, "160" ); ?> value="160">Сочи</option>
	<option <?php selected( $ld_city, "161" ); ?> value="161">Темрюк</option>
	<option <?php selected( $ld_city, "162" ); ?> value="162">Тимашевск</option>
	<option <?php selected( $ld_city, "163" ); ?> value="163">Тихорецк</option>
	<option <?php selected( $ld_city, "164" ); ?> value="164">Туапсе</option>
	<option <?php selected( $ld_city, "165" ); ?> value="165">Усть-Лабинск</option>
	<option <?php selected( $ld_city, "166" ); ?> value="166">Хадыженск</option>
	<option <?php selected( $ld_city, "167" ); ?> value="167">Ростовская область</option>
	<option <?php selected( $ld_city, "168" ); ?> value="168">Азов</option>
	<option <?php selected( $ld_city, "169" ); ?> value="169">Аксай</option>
	<option <?php selected( $ld_city, "170" ); ?> value="170">Батайск</option>
	<option <?php selected( $ld_city, "171" ); ?> value="171">Белая Калитва</option>
	<option <?php selected( $ld_city, "172" ); ?> value="172">Волгодонск</option>
	<option <?php selected( $ld_city, "173" ); ?> value="173">Гуково</option>
	<option <?php selected( $ld_city, "174" ); ?> value="174">Донецк</option>
	<option <?php selected( $ld_city, "175" ); ?> value="175">Зверево</option>
	<option <?php selected( $ld_city, "176" ); ?> value="176">Зерноград</option>
	<option <?php selected( $ld_city, "177" ); ?> value="177">Каменск-Шахтинский</option>
	<option <?php selected( $ld_city, "178" ); ?> value="178">Константиновск</option>
	<option <?php selected( $ld_city, "179" ); ?> value="179">Красный Сулин</option>
	<option <?php selected( $ld_city, "180" ); ?> value="180">Миллерово</option>
	<option <?php selected( $ld_city, "181" ); ?> value="181">Морозовск</option>
	<option <?php selected( $ld_city, "182" ); ?> value="182">Новочеркасск</option>
	<option <?php selected( $ld_city, "183" ); ?> value="183">Новошахтинск</option>
	<option <?php selected( $ld_city, "184" ); ?> value="184">Пролетарск</option>
	<option <?php selected( $ld_city, "185" ); ?> value="185">Ростов-на-Дону</option>
	<option <?php selected( $ld_city, "186" ); ?> value="186">Сальск</option>
	<option <?php selected( $ld_city, "187" ); ?> value="187">Семикаракорск</option>
	<option <?php selected( $ld_city, "188" ); ?> value="188">Таганрог</option>
	<option <?php selected( $ld_city, "189" ); ?> value="189">Цимлянск</option>
	<option <?php selected( $ld_city, "190" ); ?> value="190">Шахты</option>
	<option <?php selected( $ld_city, "191" ); ?> value="191">Свердловская область</option>
	<option <?php selected( $ld_city, "192" ); ?> value="192">Алапаевск</option>
	<option <?php selected( $ld_city, "193" ); ?> value="193">Арамиль</option>
	<option <?php selected( $ld_city, "194" ); ?> value="194">Артемовский</option>
	<option <?php selected( $ld_city, "195" ); ?> value="195">Асбест</option>
	<option <?php selected( $ld_city, "196" ); ?> value="196">Березовский</option>
	<option <?php selected( $ld_city, "197" ); ?> value="197">Богданович</option>
	<option <?php selected( $ld_city, "198" ); ?> value="198">Верхний Тагил</option>
	<option <?php selected( $ld_city, "199" ); ?> value="199">Верхняя Пышма</option>
	<option <?php selected( $ld_city, "200" ); ?> value="200">Верхняя Салда</option>
	<option <?php selected( $ld_city, "201" ); ?> value="201">Верхняя Тура</option>
	<option <?php selected( $ld_city, "202" ); ?> value="202">Верхотурье</option>
	<option <?php selected( $ld_city, "203" ); ?> value="203">Волчанск</option>
	<option <?php selected( $ld_city, "204" ); ?> value="204">Дегтярск</option>
	<option <?php selected( $ld_city, "205" ); ?> value="205">Екатеринбург</option>
	<option <?php selected( $ld_city, "206" ); ?> value="206">Заречный</option>
	<option <?php selected( $ld_city, "207" ); ?> value="207">Ивдель</option>
	<option <?php selected( $ld_city, "208" ); ?> value="208">Ирбит</option>
	<option <?php selected( $ld_city, "209" ); ?> value="209">Каменск-Уральский</option>
	<option <?php selected( $ld_city, "210" ); ?> value="210">Камышлов</option>
	<option <?php selected( $ld_city, "211" ); ?> value="211">Карпинск</option>
	<option <?php selected( $ld_city, "212" ); ?> value="212">Качканар</option>
	<option <?php selected( $ld_city, "213" ); ?> value="213">Кировград</option>
	<option <?php selected( $ld_city, "214" ); ?> value="214">Краснотурьинск</option>
	<option <?php selected( $ld_city, "215" ); ?> value="215">Красноуральск</option>
	<option <?php selected( $ld_city, "216" ); ?> value="216">Красноуфимск</option>
	<option <?php selected( $ld_city, "217" ); ?> value="217">Кушва</option>
	<option <?php selected( $ld_city, "218" ); ?> value="218">Лесной</option>
	<option <?php selected( $ld_city, "219" ); ?> value="219">Михайловск</option>
	<option <?php selected( $ld_city, "220" ); ?> value="220">Невьянск</option>
	<option <?php selected( $ld_city, "221" ); ?> value="221">Нижние Серги</option>
	<option <?php selected( $ld_city, "222" ); ?> value="222">Нижние Серги-3</option>
	<option <?php selected( $ld_city, "223" ); ?> value="223">Нижний Тагил</option>
	<option <?php selected( $ld_city, "224" ); ?> value="224">Нижняя Салда</option>
	<option <?php selected( $ld_city, "225" ); ?> value="225">Нижняя Тура</option>
	<option <?php selected( $ld_city, "226" ); ?> value="226">Новая Ляля</option>
	<option <?php selected( $ld_city, "227" ); ?> value="227">Новоуральск</option>
	<option <?php selected( $ld_city, "228" ); ?> value="228">Первоуральск</option>
	<option <?php selected( $ld_city, "229" ); ?> value="229">Полевской</option>
	<option <?php selected( $ld_city, "230" ); ?> value="230">Ревда</option>
	<option <?php selected( $ld_city, "231" ); ?> value="231">Реж</option>
	<option <?php selected( $ld_city, "232" ); ?> value="232">Североуральск</option>
	<option <?php selected( $ld_city, "233" ); ?> value="233">Серов</option>
	<option <?php selected( $ld_city, "234" ); ?> value="234">Среднеуральск</option>
	<option <?php selected( $ld_city, "235" ); ?> value="235">Сухой Лог</option>
	<option <?php selected( $ld_city, "236" ); ?> value="236">Сысерть</option>
	<option <?php selected( $ld_city, "237" ); ?> value="237">Тавда</option>
	<option <?php selected( $ld_city, "238" ); ?> value="238">Талица</option>
	<option <?php selected( $ld_city, "239" ); ?> value="239">Туринск</option>
	<option <?php selected( $ld_city, "240" ); ?> value="240">Самарская область</option>
	<option <?php selected( $ld_city, "241" ); ?> value="241">Жигулевск</option>
	<option <?php selected( $ld_city, "242" ); ?> value="242">Кинель</option>
	<option <?php selected( $ld_city, "243" ); ?> value="243">Нефтегорск</option>
	<option <?php selected( $ld_city, "244" ); ?> value="244">Новокуйбышевск</option>
	<option <?php selected( $ld_city, "245" ); ?> value="245">Октябрьск</option>
	<option <?php selected( $ld_city, "246" ); ?> value="246">Отрадный</option>
	<option <?php selected( $ld_city, "247" ); ?> value="247">Похвистнево</option>
	<option <?php selected( $ld_city, "248" ); ?> value="248">Самара</option>
	<option <?php selected( $ld_city, "249" ); ?> value="249">Сызрань</option>
	<option <?php selected( $ld_city, "250" ); ?> value="250">Тольятти</option>
	<option <?php selected( $ld_city, "251" ); ?> value="251">Чапаевск</option>
	<option <?php selected( $ld_city, "252" ); ?> value="252">Новосибирская область</option>
	<option <?php selected( $ld_city, "253" ); ?> value="253">Барабинск</option>
	<option <?php selected( $ld_city, "254" ); ?> value="254">Бердск</option>
	<option <?php selected( $ld_city, "255" ); ?> value="255">Болотное</option>
	<option <?php selected( $ld_city, "256" ); ?> value="256">Искитим</option>
	<option <?php selected( $ld_city, "257" ); ?> value="257">Карасук</option>
	<option <?php selected( $ld_city, "258" ); ?> value="258">Каргат</option>
	<option <?php selected( $ld_city, "259" ); ?> value="259">Куйбышев</option>
	<option <?php selected( $ld_city, "260" ); ?> value="260">Купино</option>
	<option <?php selected( $ld_city, "261" ); ?> value="261">Новосибирск</option>
	<option <?php selected( $ld_city, "262" ); ?> value="262">Обь</option>
	<option <?php selected( $ld_city, "263" ); ?> value="263">Татарск</option>
	<option <?php selected( $ld_city, "264" ); ?> value="264">Тогучин</option>
	<option <?php selected( $ld_city, "265" ); ?> value="265">Черепаново</option>
	<option <?php selected( $ld_city, "266" ); ?> value="266">Чулым</option>
	<option <?php selected( $ld_city, "267" ); ?> value="267">Чулым-3</option>
	<option <?php selected( $ld_city, "268" ); ?> value="268">Алтайский край</option>
	<option <?php selected( $ld_city, "269" ); ?> value="269">Алейск</option>
	<option <?php selected( $ld_city, "270" ); ?> value="270">Барнаул</option>
	<option <?php selected( $ld_city, "271" ); ?> value="271">Белокуриха</option>
	<option <?php selected( $ld_city, "272" ); ?> value="272">Бийск</option>
	<option <?php selected( $ld_city, "273" ); ?> value="273">Горняк</option>
	<option <?php selected( $ld_city, "274" ); ?> value="274">Заринск</option>
	<option <?php selected( $ld_city, "275" ); ?> value="275">Змеиногорск</option>
	<option <?php selected( $ld_city, "276" ); ?> value="276">Камень-на-Оби</option>
	<option <?php selected( $ld_city, "277" ); ?> value="277">Новоалтайск</option>
	<option <?php selected( $ld_city, "278" ); ?> value="278">Рубцовск</option>
	<option <?php selected( $ld_city, "279" ); ?> value="279">Славгород</option>
	<option <?php selected( $ld_city, "280" ); ?> value="280">Яровое</option>
	<option <?php selected( $ld_city, "281" ); ?> value="281">Амурская область</option>
	<option <?php selected( $ld_city, "282" ); ?> value="282">Белогорск</option>
	<option <?php selected( $ld_city, "283" ); ?> value="283">Благовещенск</option>
	<option <?php selected( $ld_city, "284" ); ?> value="284">Завитинск</option>
	<option <?php selected( $ld_city, "285" ); ?> value="285">Зея</option>
	<option <?php selected( $ld_city, "286" ); ?> value="286">Райчихинск</option>
	<option <?php selected( $ld_city, "287" ); ?> value="287">Свободный</option>
	<option <?php selected( $ld_city, "288" ); ?> value="288">Сковородино</option>
	<option <?php selected( $ld_city, "289" ); ?> value="289">Тында</option>
	<option <?php selected( $ld_city, "290" ); ?> value="290">Шимановск</option>
	<option <?php selected( $ld_city, "291" ); ?> value="291">Архангельская область</option>
	<option <?php selected( $ld_city, "292" ); ?> value="292">Архангельск</option>
	<option <?php selected( $ld_city, "293" ); ?> value="293">Вельск</option>
	<option <?php selected( $ld_city, "294" ); ?> value="294">Каргополь</option>
	<option <?php selected( $ld_city, "295" ); ?> value="295">Коряжма</option>
	<option <?php selected( $ld_city, "296" ); ?> value="296">Котлас</option>
	<option <?php selected( $ld_city, "297" ); ?> value="297">Мезень</option>
	<option <?php selected( $ld_city, "298" ); ?> value="298">Мирный</option>
	<option <?php selected( $ld_city, "299" ); ?> value="299">Новодвинск</option>
	<option <?php selected( $ld_city, "300" ); ?> value="300">Няндома</option>
	<option <?php selected( $ld_city, "301" ); ?> value="301">Онега</option>
	<option <?php selected( $ld_city, "302" ); ?> value="302">Северодвинск</option>
	<option <?php selected( $ld_city, "303" ); ?> value="303">Сольвычегодск</option>
	<option <?php selected( $ld_city, "304" ); ?> value="304">Шенкурск</option>
	<option <?php selected( $ld_city, "305" ); ?> value="305">Астраханская область</option>
	<option <?php selected( $ld_city, "306" ); ?> value="306">Астрахань</option>
	<option <?php selected( $ld_city, "307" ); ?> value="307">Ахтубинск</option>
	<option <?php selected( $ld_city, "308" ); ?> value="308">Знаменск</option>
	<option <?php selected( $ld_city, "309" ); ?> value="309">Камызяк</option>
	<option <?php selected( $ld_city, "310" ); ?> value="310">Нариманов</option>
	<option <?php selected( $ld_city, "311" ); ?> value="311">Харабали</option>
	<option <?php selected( $ld_city, "312" ); ?> value="312">Белгородская область</option>
	<option <?php selected( $ld_city, "313" ); ?> value="313">Алексеевка</option>
	<option <?php selected( $ld_city, "314" ); ?> value="314">Белгород</option>
	<option <?php selected( $ld_city, "315" ); ?> value="315">Бирюч</option>
	<option <?php selected( $ld_city, "316" ); ?> value="316">Валуйки</option>
	<option <?php selected( $ld_city, "317" ); ?> value="317">Грайворон</option>
	<option <?php selected( $ld_city, "318" ); ?> value="318">Губкин</option>
	<option <?php selected( $ld_city, "319" ); ?> value="319">Короча</option>
	<option <?php selected( $ld_city, "320" ); ?> value="320">Новый Оскол</option>
	<option <?php selected( $ld_city, "321" ); ?> value="321">Старый Оскол</option>
	<option <?php selected( $ld_city, "322" ); ?> value="322">Строитель</option>
	<option <?php selected( $ld_city, "323" ); ?> value="323">Шебекино</option>
	<option <?php selected( $ld_city, "324" ); ?> value="324">Брянская область</option>
	<option <?php selected( $ld_city, "325" ); ?> value="325">Брянск</option>
	<option <?php selected( $ld_city, "326" ); ?> value="326">Дятьково</option>
	<option <?php selected( $ld_city, "327" ); ?> value="327">Жуковка</option>
	<option <?php selected( $ld_city, "328" ); ?> value="328">Злынка</option>
	<option <?php selected( $ld_city, "329" ); ?> value="329">Карачев</option>
	<option <?php selected( $ld_city, "330" ); ?> value="330">Клинцы</option>
	<option <?php selected( $ld_city, "331" ); ?> value="331">Мглин</option>
	<option <?php selected( $ld_city, "332" ); ?> value="332">Новозыбков</option>
	<option <?php selected( $ld_city, "333" ); ?> value="333">Почеп</option>
	<option <?php selected( $ld_city, "334" ); ?> value="334">Севск</option>
	<option <?php selected( $ld_city, "335" ); ?> value="335">Сельцо</option>
	<option <?php selected( $ld_city, "336" ); ?> value="336">Стародуб</option>
	<option <?php selected( $ld_city, "337" ); ?> value="337">Сураж</option>
	<option <?php selected( $ld_city, "338" ); ?> value="338">Трубчевск</option>
	<option <?php selected( $ld_city, "339" ); ?> value="339">Унеча</option>
	<option <?php selected( $ld_city, "340" ); ?> value="340">Фокино</option>
	<option <?php selected( $ld_city, "341" ); ?> value="341">Владимирская область</option>
	<option <?php selected( $ld_city, "342" ); ?> value="342">Александров</option>
	<option <?php selected( $ld_city, "343" ); ?> value="343">Владимир</option>
	<option <?php selected( $ld_city, "344" ); ?> value="344">Вязники</option>
	<option <?php selected( $ld_city, "345" ); ?> value="345">Гороховец</option>
	<option <?php selected( $ld_city, "346" ); ?> value="346">Гусь-Хрустальный</option>
	<option <?php selected( $ld_city, "347" ); ?> value="347">Камешково</option>
	<option <?php selected( $ld_city, "348" ); ?> value="348">Карабаново</option>
	<option <?php selected( $ld_city, "349" ); ?> value="349">Киржач</option>
	<option <?php selected( $ld_city, "350" ); ?> value="350">Ковров</option>
	<option <?php selected( $ld_city, "351" ); ?> value="351">Кольчугино</option>
	<option <?php selected( $ld_city, "352" ); ?> value="352">Костерево</option>
	<option <?php selected( $ld_city, "353" ); ?> value="353">Курлово</option>
	<option <?php selected( $ld_city, "354" ); ?> value="354">Лакинск</option>
	<option <?php selected( $ld_city, "355" ); ?> value="355">Меленки</option>
	<option <?php selected( $ld_city, "356" ); ?> value="356">Муром</option>
	<option <?php selected( $ld_city, "357" ); ?> value="357">Петушки</option>
	<option <?php selected( $ld_city, "358" ); ?> value="358">Покров</option>
	<option <?php selected( $ld_city, "359" ); ?> value="359">Радужный</option>
	<option <?php selected( $ld_city, "360" ); ?> value="360">Собинка</option>
	<option <?php selected( $ld_city, "361" ); ?> value="361">Струнино</option>
	<option <?php selected( $ld_city, "362" ); ?> value="362">Судогда</option>
	<option <?php selected( $ld_city, "363" ); ?> value="363">Суздаль</option>
	<option <?php selected( $ld_city, "364" ); ?> value="364">Юрьев-Польский</option>
	<option <?php selected( $ld_city, "365" ); ?> value="365">Волгоградская область</option>
	<option <?php selected( $ld_city, "366" ); ?> value="366">Волгоград</option>
	<option <?php selected( $ld_city, "367" ); ?> value="367">Волжский</option>
	<option <?php selected( $ld_city, "368" ); ?> value="368">Дубовка</option>
	<option <?php selected( $ld_city, "369" ); ?> value="369">Жирновск</option>
	<option <?php selected( $ld_city, "370" ); ?> value="370">Калач-на-Дону</option>
	<option <?php selected( $ld_city, "371" ); ?> value="371">Камышин</option>
	<option <?php selected( $ld_city, "372" ); ?> value="372">Котельниково</option>
	<option <?php selected( $ld_city, "373" ); ?> value="373">Котово</option>
	<option <?php selected( $ld_city, "374" ); ?> value="374">Краснослободск</option>
	<option <?php selected( $ld_city, "375" ); ?> value="375">Ленинск</option>
	<option <?php selected( $ld_city, "376" ); ?> value="376">Михайловка</option>
	<option <?php selected( $ld_city, "377" ); ?> value="377">Николаевск</option>
	<option <?php selected( $ld_city, "378" ); ?> value="378">Новоаннинский</option>
	<option <?php selected( $ld_city, "379" ); ?> value="379">Палласовка</option>
	<option <?php selected( $ld_city, "380" ); ?> value="380">Петров Вал</option>
	<option <?php selected( $ld_city, "381" ); ?> value="381">Серафимович</option>
	<option <?php selected( $ld_city, "382" ); ?> value="382">Суровикино</option>
	<option <?php selected( $ld_city, "383" ); ?> value="383">Урюпинск</option>
	<option <?php selected( $ld_city, "384" ); ?> value="384">Фролово</option>
	<option <?php selected( $ld_city, "385" ); ?> value="385">Вологодская область</option>
	<option <?php selected( $ld_city, "386" ); ?> value="386">Бабаево</option>
	<option <?php selected( $ld_city, "387" ); ?> value="387">Белозерск</option>
	<option <?php selected( $ld_city, "388" ); ?> value="388">Великий Устюг</option>
	<option <?php selected( $ld_city, "389" ); ?> value="389">Вологда</option>
	<option <?php selected( $ld_city, "390" ); ?> value="390">Вытегра</option>
	<option <?php selected( $ld_city, "391" ); ?> value="391">Грязовец</option>
	<option <?php selected( $ld_city, "392" ); ?> value="392">Кадников</option>
	<option <?php selected( $ld_city, "393" ); ?> value="393">Кириллов</option>
	<option <?php selected( $ld_city, "394" ); ?> value="394">Красавино</option>
	<option <?php selected( $ld_city, "395" ); ?> value="395">Никольск</option>
	<option <?php selected( $ld_city, "396" ); ?> value="396">Сокол</option>
	<option <?php selected( $ld_city, "397" ); ?> value="397">Тотьма</option>
	<option <?php selected( $ld_city, "398" ); ?> value="398">Устюжна</option>
	<option <?php selected( $ld_city, "399" ); ?> value="399">Харовск</option>
	<option <?php selected( $ld_city, "400" ); ?> value="400">Череповец</option>
	<option <?php selected( $ld_city, "401" ); ?> value="401">Воронежская область</option>
	<option <?php selected( $ld_city, "402" ); ?> value="402">Бобров</option>
	<option <?php selected( $ld_city, "403" ); ?> value="403">Богучар</option>
	<option <?php selected( $ld_city, "404" ); ?> value="404">Борисоглебск</option>
	<option <?php selected( $ld_city, "405" ); ?> value="405">Бутурлиновка</option>
	<option <?php selected( $ld_city, "406" ); ?> value="406">Воронеж</option>
	<option <?php selected( $ld_city, "407" ); ?> value="407">Воронеж-45</option>
	<option <?php selected( $ld_city, "408" ); ?> value="408">Калач</option>
	<option <?php selected( $ld_city, "409" ); ?> value="409">Лиски</option>
	<option <?php selected( $ld_city, "410" ); ?> value="410">Нововоронеж</option>
	<option <?php selected( $ld_city, "411" ); ?> value="411">Новохоперск</option>
	<option <?php selected( $ld_city, "412" ); ?> value="412">Острогожск</option>
	<option <?php selected( $ld_city, "413" ); ?> value="413">Павловск</option>
	<option <?php selected( $ld_city, "414" ); ?> value="414">Поворино</option>
	<option <?php selected( $ld_city, "415" ); ?> value="415">Россошь</option>
	<option <?php selected( $ld_city, "416" ); ?> value="416">Семилуки</option>
	<option <?php selected( $ld_city, "417" ); ?> value="417">Эртиль</option>
	<option <?php selected( $ld_city, "418" ); ?> value="418">Еврейская автономная область</option>
	<option <?php selected( $ld_city, "419" ); ?> value="419">Биробиджан</option>
	<option <?php selected( $ld_city, "420" ); ?> value="420">Облучье</option>
	<option <?php selected( $ld_city, "421" ); ?> value="421">Забайкальский край</option>
	<option <?php selected( $ld_city, "422" ); ?> value="422">Балей</option>
	<option <?php selected( $ld_city, "423" ); ?> value="423">Борзя</option>
	<option <?php selected( $ld_city, "424" ); ?> value="424">Краснокаменск</option>
	<option <?php selected( $ld_city, "425" ); ?> value="425">Могоча</option>
	<option <?php selected( $ld_city, "426" ); ?> value="426">Нерчинск</option>
	<option <?php selected( $ld_city, "427" ); ?> value="427">Петровск-Забайкальский</option>
	<option <?php selected( $ld_city, "428" ); ?> value="428">Сретенск</option>
	<option <?php selected( $ld_city, "429" ); ?> value="429">Хилок</option>
	<option <?php selected( $ld_city, "430" ); ?> value="430">Чита</option>
	<option <?php selected( $ld_city, "431" ); ?> value="431">Шилка</option>
	<option <?php selected( $ld_city, "432" ); ?> value="432">Ивановская область</option>
	<option <?php selected( $ld_city, "433" ); ?> value="433">Вичуга</option>
	<option <?php selected( $ld_city, "434" ); ?> value="434">Гаврилов Посад</option>
	<option <?php selected( $ld_city, "435" ); ?> value="435">Заволжск</option>
	<option <?php selected( $ld_city, "436" ); ?> value="436">Иваново</option>
	<option <?php selected( $ld_city, "437" ); ?> value="437">Кинешма</option>
	<option <?php selected( $ld_city, "438" ); ?> value="438">Комсомольск</option>
	<option <?php selected( $ld_city, "439" ); ?> value="439">Кохма</option>
	<option <?php selected( $ld_city, "440" ); ?> value="440">Наволоки</option>
	<option <?php selected( $ld_city, "441" ); ?> value="441">Плес</option>
	<option <?php selected( $ld_city, "442" ); ?> value="442">Приволжск</option>
	<option <?php selected( $ld_city, "443" ); ?> value="443">Пучеж</option>
	<option <?php selected( $ld_city, "444" ); ?> value="444">Родники</option>
	<option <?php selected( $ld_city, "445" ); ?> value="445">Тейково</option>
	<option <?php selected( $ld_city, "446" ); ?> value="446">Фурманов</option>
	<option <?php selected( $ld_city, "447" ); ?> value="447">Шуя</option>
	<option <?php selected( $ld_city, "448" ); ?> value="448">Южа</option>
	<option <?php selected( $ld_city, "449" ); ?> value="449">Юрьевец</option>
	<option <?php selected( $ld_city, "450" ); ?> value="450">Иркутская область</option>
	<option <?php selected( $ld_city, "451" ); ?> value="451">Алзамай</option>
	<option <?php selected( $ld_city, "452" ); ?> value="452">Ангарск</option>
	<option <?php selected( $ld_city, "453" ); ?> value="453">Байкальск</option>
	<option <?php selected( $ld_city, "454" ); ?> value="454">Бирюсинск</option>
	<option <?php selected( $ld_city, "455" ); ?> value="455">Бодайбо</option>
	<option <?php selected( $ld_city, "456" ); ?> value="456">Братск</option>
	<option <?php selected( $ld_city, "457" ); ?> value="457">Вихоревка</option>
	<option <?php selected( $ld_city, "458" ); ?> value="458">Железногорск-Илимский</option>
	<option <?php selected( $ld_city, "459" ); ?> value="459">Зима</option>
	<option <?php selected( $ld_city, "460" ); ?> value="460">Иркутск</option>
	<option <?php selected( $ld_city, "461" ); ?> value="461">Киренск</option>
	<option <?php selected( $ld_city, "462" ); ?> value="462">Нижнеудинск</option>
	<option <?php selected( $ld_city, "463" ); ?> value="463">Саянск</option>
	<option <?php selected( $ld_city, "464" ); ?> value="464">Свирск</option>
	<option <?php selected( $ld_city, "465" ); ?> value="465">Слюдянка</option>
	<option <?php selected( $ld_city, "466" ); ?> value="466">Тайшет</option>
	<option <?php selected( $ld_city, "467" ); ?> value="467">Тулун</option>
	<option <?php selected( $ld_city, "468" ); ?> value="468">Усолье-Сибирское</option>
	<option <?php selected( $ld_city, "469" ); ?> value="469">Усть-Илимск</option>
	<option <?php selected( $ld_city, "470" ); ?> value="470">Усть-Кут</option>
	<option <?php selected( $ld_city, "471" ); ?> value="471">Черемхово</option>
	<option <?php selected( $ld_city, "472" ); ?> value="472">Шелехов</option>
	<option <?php selected( $ld_city, "473" ); ?> value="473">Кабардино-Балкарская республика</option>
	<option <?php selected( $ld_city, "474" ); ?> value="474">Баксан</option>
	<option <?php selected( $ld_city, "475" ); ?> value="475">Майский</option>
	<option <?php selected( $ld_city, "476" ); ?> value="476">Нальчик</option>
	<option <?php selected( $ld_city, "477" ); ?> value="477">Нарткала</option>
	<option <?php selected( $ld_city, "478" ); ?> value="478">Прохладный</option>
	<option <?php selected( $ld_city, "479" ); ?> value="479">Терек</option>
	<option <?php selected( $ld_city, "480" ); ?> value="480">Тырныауз</option>
	<option <?php selected( $ld_city, "481" ); ?> value="481">Чегем</option>
	<option <?php selected( $ld_city, "482" ); ?> value="482">Калининградская область</option>
	<option <?php selected( $ld_city, "483" ); ?> value="483">Багратионовск</option>
	<option <?php selected( $ld_city, "484" ); ?> value="484">Балтийск</option>
	<option <?php selected( $ld_city, "485" ); ?> value="485">Гвардейск</option>
	<option <?php selected( $ld_city, "486" ); ?> value="486">Гурьевск</option>
	<option <?php selected( $ld_city, "487" ); ?> value="487">Гусев</option>
	<option <?php selected( $ld_city, "488" ); ?> value="488">Зеленоградск</option>
	<option <?php selected( $ld_city, "489" ); ?> value="489">Калининград</option>
	<option <?php selected( $ld_city, "490" ); ?> value="490">Краснознаменск</option>
	<option <?php selected( $ld_city, "491" ); ?> value="491">Ладушкин</option>
	<option <?php selected( $ld_city, "492" ); ?> value="492">Мамоново</option>
	<option <?php selected( $ld_city, "493" ); ?> value="493">Неман</option>
	<option <?php selected( $ld_city, "494" ); ?> value="494">Нестеров</option>
	<option <?php selected( $ld_city, "495" ); ?> value="495">Озерск</option>
	<option <?php selected( $ld_city, "496" ); ?> value="496">Пионерский</option>
	<option <?php selected( $ld_city, "497" ); ?> value="497">Полесск</option>
	<option <?php selected( $ld_city, "498" ); ?> value="498">Правдинск</option>
	<option <?php selected( $ld_city, "499" ); ?> value="499">Приморск</option>
	<option <?php selected( $ld_city, "500" ); ?> value="500">Светлогорск</option>
	<option <?php selected( $ld_city, "501" ); ?> value="501">Светлый</option>
	<option <?php selected( $ld_city, "502" ); ?> value="502">Славск</option>
	<option <?php selected( $ld_city, "503" ); ?> value="503">Советск</option>
	<option <?php selected( $ld_city, "504" ); ?> value="504">Черняховск</option>
	<option <?php selected( $ld_city, "505" ); ?> value="505">Калужская область</option>
	<option <?php selected( $ld_city, "506" ); ?> value="506">Балабаново</option>
	<option <?php selected( $ld_city, "507" ); ?> value="507">Белоусово</option>
	<option <?php selected( $ld_city, "508" ); ?> value="508">Боровск</option>
	<option <?php selected( $ld_city, "509" ); ?> value="509">Ермолино</option>
	<option <?php selected( $ld_city, "510" ); ?> value="510">Жиздра</option>
	<option <?php selected( $ld_city, "511" ); ?> value="511">Жуков</option>
	<option <?php selected( $ld_city, "512" ); ?> value="512">Калуга</option>
	<option <?php selected( $ld_city, "513" ); ?> value="513">Киров</option>
	<option <?php selected( $ld_city, "514" ); ?> value="514">Козельск</option>
	<option <?php selected( $ld_city, "515" ); ?> value="515">Кондрово</option>
	<option <?php selected( $ld_city, "516" ); ?> value="516">Кременки</option>
	<option <?php selected( $ld_city, "517" ); ?> value="517">Людиново</option>
	<option <?php selected( $ld_city, "518" ); ?> value="518">Малоярославец</option>
	<option <?php selected( $ld_city, "519" ); ?> value="519">Медынь</option>
	<option <?php selected( $ld_city, "520" ); ?> value="520">Мещовск</option>
	<option <?php selected( $ld_city, "521" ); ?> value="521">Мосальск</option>
	<option <?php selected( $ld_city, "522" ); ?> value="522">Обнинск</option>
	<option <?php selected( $ld_city, "523" ); ?> value="523">Сосенский</option>
	<option <?php selected( $ld_city, "524" ); ?> value="524">Спас-Деменск</option>
	<option <?php selected( $ld_city, "525" ); ?> value="525">Сухиничи</option>
	<option <?php selected( $ld_city, "526" ); ?> value="526">Таруса</option>
	<option <?php selected( $ld_city, "527" ); ?> value="527">Юхнов</option>
	<option <?php selected( $ld_city, "528" ); ?> value="528">Юхнов-1</option>
	<option <?php selected( $ld_city, "529" ); ?> value="529">Юхнов-2</option>
	<option <?php selected( $ld_city, "530" ); ?> value="530">Камчатский край</option>
	<option <?php selected( $ld_city, "531" ); ?> value="531">Вилючинск</option>
	<option <?php selected( $ld_city, "532" ); ?> value="532">Елизово</option>
	<option <?php selected( $ld_city, "533" ); ?> value="533">Петропавловск-Камчатский</option>
	<option <?php selected( $ld_city, "534" ); ?> value="534">Карачаево-Черкесская республика</option>
	<option <?php selected( $ld_city, "535" ); ?> value="535">Карачаевск</option>
	<option <?php selected( $ld_city, "536" ); ?> value="536">Теберда</option>
	<option <?php selected( $ld_city, "537" ); ?> value="537">Усть-Джегута</option>
	<option <?php selected( $ld_city, "538" ); ?> value="538">Черкесск</option>
	<option <?php selected( $ld_city, "539" ); ?> value="539">Кемеровская область</option>
	<option <?php selected( $ld_city, "540" ); ?> value="540">Анжеро-Судженск</option>
	<option <?php selected( $ld_city, "541" ); ?> value="541">Белово</option>
	<option <?php selected( $ld_city, "542" ); ?> value="542">Березовский</option>
	<option <?php selected( $ld_city, "543" ); ?> value="543">Гурьевск</option>
	<option <?php selected( $ld_city, "544" ); ?> value="544">Калтан</option>
	<option <?php selected( $ld_city, "545" ); ?> value="545">Кемерово</option>
	<option <?php selected( $ld_city, "546" ); ?> value="546">Киселевск</option>
	<option <?php selected( $ld_city, "547" ); ?> value="547">Ленинск-Кузнецкий</option>
	<option <?php selected( $ld_city, "548" ); ?> value="548">Мариинск</option>
	<option <?php selected( $ld_city, "549" ); ?> value="549">Междуреченск</option>
	<option <?php selected( $ld_city, "550" ); ?> value="550">Мыски</option>
	<option <?php selected( $ld_city, "551" ); ?> value="551">Новокузнецк</option>
	<option <?php selected( $ld_city, "552" ); ?> value="552">Осинники</option>
	<option <?php selected( $ld_city, "553" ); ?> value="553">Полысаево</option>
	<option <?php selected( $ld_city, "554" ); ?> value="554">Прокопьевск</option>
	<option <?php selected( $ld_city, "555" ); ?> value="555">Салаир</option>
	<option <?php selected( $ld_city, "556" ); ?> value="556">Тайга</option>
	<option <?php selected( $ld_city, "557" ); ?> value="557">Таштагол</option>
	<option <?php selected( $ld_city, "558" ); ?> value="558">Топки</option>
	<option <?php selected( $ld_city, "559" ); ?> value="559">Юрга</option>
	<option <?php selected( $ld_city, "560" ); ?> value="560">Кировская область</option>
	<option <?php selected( $ld_city, "561" ); ?> value="561">Белая Холуница</option>
	<option <?php selected( $ld_city, "562" ); ?> value="562">Вятские Поляны</option>
	<option <?php selected( $ld_city, "563" ); ?> value="563">Зуевка</option>
	<option <?php selected( $ld_city, "564" ); ?> value="564">Киров</option>
	<option <?php selected( $ld_city, "565" ); ?> value="565">Кирово-Чепецк</option>
	<option <?php selected( $ld_city, "566" ); ?> value="566">Кирс</option>
	<option <?php selected( $ld_city, "567" ); ?> value="567">Котельнич</option>
	<option <?php selected( $ld_city, "568" ); ?> value="568">Луза</option>
	<option <?php selected( $ld_city, "569" ); ?> value="569">Малмыж</option>
	<option <?php selected( $ld_city, "570" ); ?> value="570">Мураши</option>
	<option <?php selected( $ld_city, "571" ); ?> value="571">Нолинск</option>
	<option <?php selected( $ld_city, "572" ); ?> value="572">Омутнинск</option>
	<option <?php selected( $ld_city, "573" ); ?> value="573">Орлов</option>
	<option <?php selected( $ld_city, "574" ); ?> value="574">Слободской</option>
	<option <?php selected( $ld_city, "575" ); ?> value="575">Советск</option>
	<option <?php selected( $ld_city, "576" ); ?> value="576">Сосновка</option>
	<option <?php selected( $ld_city, "577" ); ?> value="577">Уржум</option>
	<option <?php selected( $ld_city, "578" ); ?> value="578">Яранск</option>
	<option <?php selected( $ld_city, "579" ); ?> value="579">Костромская область</option>
	<option <?php selected( $ld_city, "580" ); ?> value="580">Буй</option>
	<option <?php selected( $ld_city, "581" ); ?> value="581">Волгореченск</option>
	<option <?php selected( $ld_city, "582" ); ?> value="582">Галич</option>
	<option <?php selected( $ld_city, "583" ); ?> value="583">Кологрив</option>
	<option <?php selected( $ld_city, "584" ); ?> value="584">Кострома</option>
	<option <?php selected( $ld_city, "585" ); ?> value="585">Макарьев</option>
	<option <?php selected( $ld_city, "586" ); ?> value="586">Мантурово</option>
	<option <?php selected( $ld_city, "587" ); ?> value="587">Нерехта</option>
	<option <?php selected( $ld_city, "588" ); ?> value="588">Нея</option>
	<option <?php selected( $ld_city, "589" ); ?> value="589">Солигалич</option>
	<option <?php selected( $ld_city, "590" ); ?> value="590">Чухлома</option>
	<option <?php selected( $ld_city, "591" ); ?> value="591">Шарья</option>
	<option <?php selected( $ld_city, "592" ); ?> value="592">Красноярский край</option>
	<option <?php selected( $ld_city, "593" ); ?> value="593">Артемовск</option>
	<option <?php selected( $ld_city, "594" ); ?> value="594">Ачинск</option>
	<option <?php selected( $ld_city, "595" ); ?> value="595">Боготол</option>
	<option <?php selected( $ld_city, "596" ); ?> value="596">Бородино</option>
	<option <?php selected( $ld_city, "597" ); ?> value="597">Дивногорск</option>
	<option <?php selected( $ld_city, "598" ); ?> value="598">Дудинка</option>
	<option <?php selected( $ld_city, "599" ); ?> value="599">Енисейск</option>
	<option <?php selected( $ld_city, "600" ); ?> value="600">Железногорск</option>
	<option <?php selected( $ld_city, "601" ); ?> value="601">Заозерный</option>
	<option <?php selected( $ld_city, "602" ); ?> value="602">Заозерный</option>
	<option <?php selected( $ld_city, "603" ); ?> value="603">Зеленогорск</option>
	<option <?php selected( $ld_city, "604" ); ?> value="604">Игарка</option>
	<option <?php selected( $ld_city, "605" ); ?> value="605">Иланский</option>
	<option <?php selected( $ld_city, "606" ); ?> value="606">Кайеркан</option>
	<option <?php selected( $ld_city, "607" ); ?> value="607">Канск</option>
	<option <?php selected( $ld_city, "608" ); ?> value="608">Кодинск</option>
	<option <?php selected( $ld_city, "609" ); ?> value="609">Красноярск</option>
	<option <?php selected( $ld_city, "610" ); ?> value="610">Лесосибирск</option>
	<option <?php selected( $ld_city, "611" ); ?> value="611">Минусинск</option>
	<option <?php selected( $ld_city, "612" ); ?> value="612">Назарово</option>
	<option <?php selected( $ld_city, "613" ); ?> value="613">Норильск</option>
	<option <?php selected( $ld_city, "614" ); ?> value="614">Сосновоборск</option>
	<option <?php selected( $ld_city, "615" ); ?> value="615">Талнах</option>
	<option <?php selected( $ld_city, "616" ); ?> value="616">Ужур</option>
	<option <?php selected( $ld_city, "617" ); ?> value="617">Уяр</option>
	<option <?php selected( $ld_city, "618" ); ?> value="618">Шарыпово</option>
	<option <?php selected( $ld_city, "619" ); ?> value="619">Курганская область</option>
	<option <?php selected( $ld_city, "620" ); ?> value="620">Далматово</option>
	<option <?php selected( $ld_city, "621" ); ?> value="621">Катайск</option>
	<option <?php selected( $ld_city, "622" ); ?> value="622">Курган</option>
	<option <?php selected( $ld_city, "623" ); ?> value="623">Куртамыш</option>
	<option <?php selected( $ld_city, "624" ); ?> value="624">Макушино</option>
	<option <?php selected( $ld_city, "625" ); ?> value="625">Петухово</option>
	<option <?php selected( $ld_city, "626" ); ?> value="626">Шадринск</option>
	<option <?php selected( $ld_city, "627" ); ?> value="627">Шумиха</option>
	<option <?php selected( $ld_city, "628" ); ?> value="628">Щучье</option>
	<option <?php selected( $ld_city, "629" ); ?> value="629">Курская область</option>
	<option <?php selected( $ld_city, "630" ); ?> value="630">Дмитриев-Льговский</option>
	<option <?php selected( $ld_city, "631" ); ?> value="631">Железногорск</option>
	<option <?php selected( $ld_city, "632" ); ?> value="632">Курск</option>
	<option <?php selected( $ld_city, "633" ); ?> value="633">Курчатов</option>
	<option <?php selected( $ld_city, "634" ); ?> value="634">Льгов</option>
	<option <?php selected( $ld_city, "635" ); ?> value="635">Обоянь</option>
	<option <?php selected( $ld_city, "636" ); ?> value="636">Рыльск</option>
	<option <?php selected( $ld_city, "637" ); ?> value="637">Суджа</option>
	<option <?php selected( $ld_city, "638" ); ?> value="638">Фатеж</option>
	<option <?php selected( $ld_city, "639" ); ?> value="639">Щигры</option>
	<option <?php selected( $ld_city, "640" ); ?> value="640">Ленинградская область</option>
	<option <?php selected( $ld_city, "641" ); ?> value="641">Бокситогорск</option>
	<option <?php selected( $ld_city, "642" ); ?> value="642">Волосово</option>
	<option <?php selected( $ld_city, "643" ); ?> value="643">Волхов</option>
	<option <?php selected( $ld_city, "644" ); ?> value="644">Всеволожск</option>
	<option <?php selected( $ld_city, "645" ); ?> value="645">Выборг</option>
	<option <?php selected( $ld_city, "646" ); ?> value="646">Высоцк</option>
	<option <?php selected( $ld_city, "647" ); ?> value="647">Гатчина</option>
	<option <?php selected( $ld_city, "648" ); ?> value="648">Ивангород</option>
	<option <?php selected( $ld_city, "649" ); ?> value="649">Каменногорск</option>
	<option <?php selected( $ld_city, "650" ); ?> value="650">Кингисепп</option>
	<option <?php selected( $ld_city, "651" ); ?> value="651">Кириши</option>
	<option <?php selected( $ld_city, "652" ); ?> value="652">Кировск</option>
	<option <?php selected( $ld_city, "653" ); ?> value="653">Коммунар</option>
	<option <?php selected( $ld_city, "654" ); ?> value="654">Лодейное Поле</option>
	<option <?php selected( $ld_city, "655" ); ?> value="655">Луга</option>
	<option <?php selected( $ld_city, "656" ); ?> value="656">Любань</option>
	<option <?php selected( $ld_city, "657" ); ?> value="657">Никольское</option>
	<option <?php selected( $ld_city, "658" ); ?> value="658">Новая Ладога</option>
	<option <?php selected( $ld_city, "659" ); ?> value="659">Отрадное</option>
	<option <?php selected( $ld_city, "660" ); ?> value="660">Пикалево</option>
	<option <?php selected( $ld_city, "661" ); ?> value="661">Подпорожье</option>
	<option <?php selected( $ld_city, "662" ); ?> value="662">Приморск</option>
	<option <?php selected( $ld_city, "663" ); ?> value="663">Приозерск</option>
	<option <?php selected( $ld_city, "664" ); ?> value="664">Светогорск</option>
	<option <?php selected( $ld_city, "665" ); ?> value="665">Сертолово</option>
	<option <?php selected( $ld_city, "666" ); ?> value="666">Сланцы</option>
	<option <?php selected( $ld_city, "667" ); ?> value="667">Сосновый Бор</option>
	<option <?php selected( $ld_city, "668" ); ?> value="668">Сясьстрой</option>
	<option <?php selected( $ld_city, "669" ); ?> value="669">Тихвин</option>
	<option <?php selected( $ld_city, "670" ); ?> value="670">Тосно</option>
	<option <?php selected( $ld_city, "671" ); ?> value="671">Шлиссельбург</option>
	<option <?php selected( $ld_city, "672" ); ?> value="672">Липецкая область</option>
	<option <?php selected( $ld_city, "673" ); ?> value="673">Грязи</option>
	<option <?php selected( $ld_city, "674" ); ?> value="674">Данков</option>
	<option <?php selected( $ld_city, "675" ); ?> value="675">Елец</option>
	<option <?php selected( $ld_city, "676" ); ?> value="676">Задонск</option>
	<option <?php selected( $ld_city, "677" ); ?> value="677">Лебедянь</option>
	<option <?php selected( $ld_city, "678" ); ?> value="678">Липецк</option>
	<option <?php selected( $ld_city, "679" ); ?> value="679">Усмань</option>
	<option <?php selected( $ld_city, "680" ); ?> value="680">Чаплыгин</option>
	<option <?php selected( $ld_city, "681" ); ?> value="681">Магаданская область</option>
	<option <?php selected( $ld_city, "682" ); ?> value="682">Магадан</option>
	<option <?php selected( $ld_city, "683" ); ?> value="683">Сусуман</option>
	<option <?php selected( $ld_city, "684" ); ?> value="684">Мурманская область</option>
	<option <?php selected( $ld_city, "685" ); ?> value="685">Апатиты</option>
	<option <?php selected( $ld_city, "686" ); ?> value="686">Гаджиево</option>
	<option <?php selected( $ld_city, "687" ); ?> value="687">Заозерск</option>
	<option <?php selected( $ld_city, "688" ); ?> value="688">Заполярный</option>
	<option <?php selected( $ld_city, "689" ); ?> value="689">Кандалакша</option>
	<option <?php selected( $ld_city, "690" ); ?> value="690">Кировск</option>
	<option <?php selected( $ld_city, "691" ); ?> value="691">Ковдор</option>
	<option <?php selected( $ld_city, "692" ); ?> value="692">Кола</option>
	<option <?php selected( $ld_city, "693" ); ?> value="693">Мончегорск</option>
	<option <?php selected( $ld_city, "694" ); ?> value="694">Мурманск</option>
	<option <?php selected( $ld_city, "695" ); ?> value="695">Оленегорск</option>
	<option <?php selected( $ld_city, "696" ); ?> value="696">Оленегорск-1</option>
	<option <?php selected( $ld_city, "697" ); ?> value="697">Оленегорск-2</option>
	<option <?php selected( $ld_city, "698" ); ?> value="698">Оленегорск-4</option>
	<option <?php selected( $ld_city, "699" ); ?> value="699">Островной</option>
	<option <?php selected( $ld_city, "700" ); ?> value="700">Полярные Зори</option>
	<option <?php selected( $ld_city, "701" ); ?> value="701">Полярный</option>
	<option <?php selected( $ld_city, "702" ); ?> value="702">Североморск</option>
	<option <?php selected( $ld_city, "703" ); ?> value="703">Снежногорск</option>
	<option <?php selected( $ld_city, "704" ); ?> value="704">Ненецкий автономный округ</option>
	<option <?php selected( $ld_city, "705" ); ?> value="705">Нарьян-Мар</option>
	<option <?php selected( $ld_city, "706" ); ?> value="706">Новгородская область</option>
	<option <?php selected( $ld_city, "707" ); ?> value="707">Боровичи</option>
	<option <?php selected( $ld_city, "708" ); ?> value="708">Валдай</option>
	<option <?php selected( $ld_city, "709" ); ?> value="709">Великий Новгород</option>
	<option <?php selected( $ld_city, "710" ); ?> value="710">Малая Вишера</option>
	<option <?php selected( $ld_city, "711" ); ?> value="711">Окуловка</option>
	<option <?php selected( $ld_city, "712" ); ?> value="712">Пестово</option>
	<option <?php selected( $ld_city, "713" ); ?> value="713">Сольцы</option>
	<option <?php selected( $ld_city, "714" ); ?> value="714">Сольцы 2</option>
	<option <?php selected( $ld_city, "715" ); ?> value="715">Старая Русса</option>
	<option <?php selected( $ld_city, "716" ); ?> value="716">Холм</option>
	<option <?php selected( $ld_city, "717" ); ?> value="717">Чудово</option>
	<option <?php selected( $ld_city, "718" ); ?> value="718">Омская область</option>
	<option <?php selected( $ld_city, "719" ); ?> value="719">Исилькуль</option>
	<option <?php selected( $ld_city, "720" ); ?> value="720">Калачинск</option>
	<option <?php selected( $ld_city, "721" ); ?> value="721">Называевск</option>
	<option <?php selected( $ld_city, "722" ); ?> value="722">Омск</option>
	<option <?php selected( $ld_city, "723" ); ?> value="723">Тара</option>
	<option <?php selected( $ld_city, "724" ); ?> value="724">Тюкалинск</option>
	<option <?php selected( $ld_city, "725" ); ?> value="725">Оренбургская область</option>
	<option <?php selected( $ld_city, "726" ); ?> value="726">Абдулино</option>
	<option <?php selected( $ld_city, "727" ); ?> value="727">Бугуруслан</option>
	<option <?php selected( $ld_city, "728" ); ?> value="728">Бузулук</option>
	<option <?php selected( $ld_city, "729" ); ?> value="729">Гай</option>
	<option <?php selected( $ld_city, "730" ); ?> value="730">Кувандык</option>
	<option <?php selected( $ld_city, "731" ); ?> value="731">Медногорск</option>
	<option <?php selected( $ld_city, "732" ); ?> value="732">Новотроицк</option>
	<option <?php selected( $ld_city, "733" ); ?> value="733">Оренбург</option>
	<option <?php selected( $ld_city, "734" ); ?> value="734">Орск</option>
	<option <?php selected( $ld_city, "735" ); ?> value="735">Соль-Илецк</option>
	<option <?php selected( $ld_city, "736" ); ?> value="736">Сорочинск</option>
	<option <?php selected( $ld_city, "737" ); ?> value="737">Ясный</option>
	<option <?php selected( $ld_city, "738" ); ?> value="738">Орловская область</option>
	<option <?php selected( $ld_city, "739" ); ?> value="739">Болхов</option>
	<option <?php selected( $ld_city, "740" ); ?> value="740">Дмитровск</option>
	<option <?php selected( $ld_city, "741" ); ?> value="741">Ливны</option>
	<option <?php selected( $ld_city, "742" ); ?> value="742">Малоархангельск</option>
	<option <?php selected( $ld_city, "743" ); ?> value="743">Мценск</option>
	<option <?php selected( $ld_city, "744" ); ?> value="744">Новосиль</option>
	<option <?php selected( $ld_city, "745" ); ?> value="745">Орел</option>
	<option <?php selected( $ld_city, "746" ); ?> value="746">Пензенская область</option>
	<option <?php selected( $ld_city, "747" ); ?> value="747">Белинский</option>
	<option <?php selected( $ld_city, "748" ); ?> value="748">Городище</option>
	<option <?php selected( $ld_city, "749" ); ?> value="749">Заречный</option>
	<option <?php selected( $ld_city, "750" ); ?> value="750">Каменка</option>
	<option <?php selected( $ld_city, "751" ); ?> value="751">Кузнецк</option>
	<option <?php selected( $ld_city, "752" ); ?> value="752">Кузнецк-12</option>
	<option <?php selected( $ld_city, "753" ); ?> value="753">Кузнецк-8</option>
	<option <?php selected( $ld_city, "754" ); ?> value="754">Нижний Ломов</option>
	<option <?php selected( $ld_city, "755" ); ?> value="755">Никольск</option>
	<option <?php selected( $ld_city, "756" ); ?> value="756">Пенза</option>
	<option <?php selected( $ld_city, "757" ); ?> value="757">Сердобск</option>
	<option <?php selected( $ld_city, "758" ); ?> value="758">Спасск</option>
	<option <?php selected( $ld_city, "759" ); ?> value="759">Сурск</option>
	<option <?php selected( $ld_city, "760" ); ?> value="760">Пермский край</option>
	<option <?php selected( $ld_city, "761" ); ?> value="761">Александровск</option>
	<option <?php selected( $ld_city, "762" ); ?> value="762">Березники</option>
	<option <?php selected( $ld_city, "763" ); ?> value="763">Верещагино</option>
	<option <?php selected( $ld_city, "764" ); ?> value="764">Горнозаводск</option>
	<option <?php selected( $ld_city, "765" ); ?> value="765">Гремячинск</option>
	<option <?php selected( $ld_city, "766" ); ?> value="766">Губаха</option>
	<option <?php selected( $ld_city, "767" ); ?> value="767">Добрянка</option>
	<option <?php selected( $ld_city, "768" ); ?> value="768">Кизел</option>
	<option <?php selected( $ld_city, "769" ); ?> value="769">Красновишерск</option>
	<option <?php selected( $ld_city, "770" ); ?> value="770">Краснокамск</option>
	<option <?php selected( $ld_city, "771" ); ?> value="771">Кудымкар</option>
	<option <?php selected( $ld_city, "772" ); ?> value="772">Кунгур</option>
	<option <?php selected( $ld_city, "773" ); ?> value="773">Лысьва</option>
	<option <?php selected( $ld_city, "774" ); ?> value="774">Нытва</option>
	<option <?php selected( $ld_city, "775" ); ?> value="775">Оса</option>
	<option <?php selected( $ld_city, "776" ); ?> value="776">Оханск</option>
	<option <?php selected( $ld_city, "777" ); ?> value="777">Очер</option>
	<option <?php selected( $ld_city, "778" ); ?> value="778">Пермь</option>
	<option <?php selected( $ld_city, "779" ); ?> value="779">Соликамск</option>
	<option <?php selected( $ld_city, "780" ); ?> value="780">Усолье</option>
	<option <?php selected( $ld_city, "781" ); ?> value="781">Чайковский</option>
	<option <?php selected( $ld_city, "782" ); ?> value="782">Чердынь</option>
	<option <?php selected( $ld_city, "783" ); ?> value="783">Чермоз</option>
	<option <?php selected( $ld_city, "784" ); ?> value="784">Чернушка</option>
	<option <?php selected( $ld_city, "785" ); ?> value="785">Чусовой</option>
	<option <?php selected( $ld_city, "786" ); ?> value="786">Приморский край</option>
	<option <?php selected( $ld_city, "787" ); ?> value="787">Арсеньев</option>
	<option <?php selected( $ld_city, "788" ); ?> value="788">Артем</option>
	<option <?php selected( $ld_city, "789" ); ?> value="789">Большой Камень</option>
	<option <?php selected( $ld_city, "790" ); ?> value="790">Владивосток</option>
	<option <?php selected( $ld_city, "791" ); ?> value="791">Дальнегорск</option>
	<option <?php selected( $ld_city, "792" ); ?> value="792">Дальнереченск</option>
	<option <?php selected( $ld_city, "793" ); ?> value="793">Лесозаводск</option>
	<option <?php selected( $ld_city, "794" ); ?> value="794">Находка</option>
	<option <?php selected( $ld_city, "795" ); ?> value="795">Партизанск</option>
	<option <?php selected( $ld_city, "796" ); ?> value="796">Спасск-Дальний</option>
	<option <?php selected( $ld_city, "797" ); ?> value="797">Уссурийск</option>
	<option <?php selected( $ld_city, "798" ); ?> value="798">Фокино</option>
	<option <?php selected( $ld_city, "799" ); ?> value="799">Псковская область</option>
	<option <?php selected( $ld_city, "800" ); ?> value="800">Великие Луки</option>
	<option <?php selected( $ld_city, "801" ); ?> value="801">Гдов</option>
	<option <?php selected( $ld_city, "802" ); ?> value="802">Дно</option>
	<option <?php selected( $ld_city, "803" ); ?> value="803">Невель</option>
	<option <?php selected( $ld_city, "804" ); ?> value="804">Новоржев</option>
	<option <?php selected( $ld_city, "805" ); ?> value="805">Новосокольники</option>
	<option <?php selected( $ld_city, "806" ); ?> value="806">Опочка</option>
	<option <?php selected( $ld_city, "807" ); ?> value="807">Остров</option>
	<option <?php selected( $ld_city, "808" ); ?> value="808">Печоры</option>
	<option <?php selected( $ld_city, "809" ); ?> value="809">Порхов</option>
	<option <?php selected( $ld_city, "810" ); ?> value="810">Псков</option>
	<option <?php selected( $ld_city, "811" ); ?> value="811">Пустошка</option>
	<option <?php selected( $ld_city, "812" ); ?> value="812">Пыталово</option>
	<option <?php selected( $ld_city, "813" ); ?> value="813">Себеж</option>
	<option <?php selected( $ld_city, "814" ); ?> value="814">Республика Адыгея</option>
	<option <?php selected( $ld_city, "815" ); ?> value="815">Адыгейск</option>
	<option <?php selected( $ld_city, "816" ); ?> value="816">Майкоп</option>
	<option <?php selected( $ld_city, "817" ); ?> value="817">Республика Алтай</option>
	<option <?php selected( $ld_city, "818" ); ?> value="818">Горно-Алтайск</option>
	<option <?php selected( $ld_city, "819" ); ?> value="819">Республика Башкортостан</option>
	<option <?php selected( $ld_city, "820" ); ?> value="820">Агидель</option>
	<option <?php selected( $ld_city, "821" ); ?> value="821">Баймак</option>
	<option <?php selected( $ld_city, "822" ); ?> value="822">Белебей</option>
	<option <?php selected( $ld_city, "823" ); ?> value="823">Белорецк</option>
	<option <?php selected( $ld_city, "824" ); ?> value="824">Бирск</option>
	<option <?php selected( $ld_city, "825" ); ?> value="825">Благовещенск</option>
	<option <?php selected( $ld_city, "826" ); ?> value="826">Давлеканово</option>
	<option <?php selected( $ld_city, "827" ); ?> value="827">Дюртюли</option>
	<option <?php selected( $ld_city, "828" ); ?> value="828">Ишимбай</option>
	<option <?php selected( $ld_city, "829" ); ?> value="829">Кумертау</option>
	<option <?php selected( $ld_city, "830" ); ?> value="830">Межгорье</option>
	<option <?php selected( $ld_city, "831" ); ?> value="831">Мелеуз</option>
	<option <?php selected( $ld_city, "832" ); ?> value="832">Нефтекамск</option>
	<option <?php selected( $ld_city, "833" ); ?> value="833">Октябрьский</option>
	<option <?php selected( $ld_city, "834" ); ?> value="834">Салават</option>
	<option <?php selected( $ld_city, "835" ); ?> value="835">Сибай</option>
	<option <?php selected( $ld_city, "836" ); ?> value="836">Стерлитамак</option>
	<option <?php selected( $ld_city, "837" ); ?> value="837">Туймазы</option>
	<option <?php selected( $ld_city, "838" ); ?> value="838">Уфа</option>
	<option <?php selected( $ld_city, "839" ); ?> value="839">Учалы</option>
	<option <?php selected( $ld_city, "840" ); ?> value="840">Янаул</option>
	<option <?php selected( $ld_city, "841" ); ?> value="841">Республика Бурятия</option>
	<option <?php selected( $ld_city, "842" ); ?> value="842">Бабушкин</option>
	<option <?php selected( $ld_city, "843" ); ?> value="843">Гусиноозерск</option>
	<option <?php selected( $ld_city, "844" ); ?> value="844">Закаменск</option>
	<option <?php selected( $ld_city, "845" ); ?> value="845">Кяхта</option>
	<option <?php selected( $ld_city, "846" ); ?> value="846">Северобайкальск</option>
	<option <?php selected( $ld_city, "847" ); ?> value="847">Улан-Удэ</option>
	<option <?php selected( $ld_city, "848" ); ?> value="848">Республика Дагестан</option>
	<option <?php selected( $ld_city, "849" ); ?> value="849">Буйнакск</option>
	<option <?php selected( $ld_city, "850" ); ?> value="850">Дагестанские Огни</option>
	<option <?php selected( $ld_city, "851" ); ?> value="851">Дербент</option>
	<option <?php selected( $ld_city, "852" ); ?> value="852">Избербаш</option>
	<option <?php selected( $ld_city, "853" ); ?> value="853">Каспийск</option>
	<option <?php selected( $ld_city, "854" ); ?> value="854">Кизилюрт</option>
	<option <?php selected( $ld_city, "855" ); ?> value="855">Кизляр</option>
	<option <?php selected( $ld_city, "856" ); ?> value="856">Махачкала</option>
	<option <?php selected( $ld_city, "857" ); ?> value="857">Хасавюрт</option>
	<option <?php selected( $ld_city, "858" ); ?> value="858">Южно-Сухокумск</option>
	<option <?php selected( $ld_city, "859" ); ?> value="859">Республика Ингушетия</option>
	<option <?php selected( $ld_city, "860" ); ?> value="860">Карабулак</option>
	<option <?php selected( $ld_city, "861" ); ?> value="861">Магас</option>
	<option <?php selected( $ld_city, "862" ); ?> value="862">Малгобек</option>
	<option <?php selected( $ld_city, "863" ); ?> value="863">Назрань</option>
	<option <?php selected( $ld_city, "864" ); ?> value="864">Республика Калмыкия</option>
	<option <?php selected( $ld_city, "865" ); ?> value="865">Городовиковск</option>
	<option <?php selected( $ld_city, "866" ); ?> value="866">Лагань</option>
	<option <?php selected( $ld_city, "867" ); ?> value="867">Элиста</option>
	<option <?php selected( $ld_city, "868" ); ?> value="868">Республика Карелия</option>
	<option <?php selected( $ld_city, "869" ); ?> value="869">Беломорск</option>
	<option <?php selected( $ld_city, "870" ); ?> value="870">Кемь</option>
	<option <?php selected( $ld_city, "871" ); ?> value="871">Кондопога</option>
	<option <?php selected( $ld_city, "872" ); ?> value="872">Костомукша</option>
	<option <?php selected( $ld_city, "873" ); ?> value="873">Лахденпохья</option>
	<option <?php selected( $ld_city, "874" ); ?> value="874">Медвежьегорск</option>
	<option <?php selected( $ld_city, "875" ); ?> value="875">Олонец</option>
	<option <?php selected( $ld_city, "876" ); ?> value="876">Петрозаводск</option>
	<option <?php selected( $ld_city, "877" ); ?> value="877">Питкяранта</option>
	<option <?php selected( $ld_city, "878" ); ?> value="878">Пудож</option>
	<option <?php selected( $ld_city, "879" ); ?> value="879">Сегежа</option>
	<option <?php selected( $ld_city, "880" ); ?> value="880">Сортавала</option>
	<option <?php selected( $ld_city, "881" ); ?> value="881">Суоярви</option>
	<option <?php selected( $ld_city, "882" ); ?> value="882">Республика Коми</option>
	<option <?php selected( $ld_city, "883" ); ?> value="883">Воркута</option>
	<option <?php selected( $ld_city, "884" ); ?> value="884">Вуктыл</option>
	<option <?php selected( $ld_city, "885" ); ?> value="885">Емва</option>
	<option <?php selected( $ld_city, "886" ); ?> value="886">Инта</option>
	<option <?php selected( $ld_city, "887" ); ?> value="887">Микунь</option>
	<option <?php selected( $ld_city, "888" ); ?> value="888">Печора</option>
	<option <?php selected( $ld_city, "889" ); ?> value="889">Сосногорск</option>
	<option <?php selected( $ld_city, "890" ); ?> value="890">Сыктывкар</option>
	<option <?php selected( $ld_city, "891" ); ?> value="891">Усинск</option>
	<option <?php selected( $ld_city, "892" ); ?> value="892">Ухта</option>
	<option <?php selected( $ld_city, "893" ); ?> value="893">Республика Марий Эл</option>
	<option <?php selected( $ld_city, "894" ); ?> value="894">Волжск</option>
	<option <?php selected( $ld_city, "895" ); ?> value="895">Звенигово</option>
	<option <?php selected( $ld_city, "896" ); ?> value="896">Йошкар-Ола</option>
	<option <?php selected( $ld_city, "897" ); ?> value="897">Козьмодемьянск</option>
	<option <?php selected( $ld_city, "898" ); ?> value="898">Республика Мордовия</option>
	<option <?php selected( $ld_city, "899" ); ?> value="899">Ардатов</option>
	<option <?php selected( $ld_city, "900" ); ?> value="900">Инсар</option>
	<option <?php selected( $ld_city, "901" ); ?> value="901">Ковылкино</option>
	<option <?php selected( $ld_city, "902" ); ?> value="902">Краснослободск</option>
	<option <?php selected( $ld_city, "903" ); ?> value="903">Рузаевка</option>
	<option <?php selected( $ld_city, "904" ); ?> value="904">Саранск</option>
	<option <?php selected( $ld_city, "905" ); ?> value="905">Темников</option>
	<option <?php selected( $ld_city, "906" ); ?> value="906">Республика Саха (Якутия)</option>
	<option <?php selected( $ld_city, "907" ); ?> value="907">Алдан</option>
	<option <?php selected( $ld_city, "908" ); ?> value="908">Верхоянск</option>
	<option <?php selected( $ld_city, "909" ); ?> value="909">Вилюйск</option>
	<option <?php selected( $ld_city, "910" ); ?> value="910">Ленск</option>
	<option <?php selected( $ld_city, "911" ); ?> value="911">Мирный</option>
	<option <?php selected( $ld_city, "912" ); ?> value="912">Нерюнгри</option>
	<option <?php selected( $ld_city, "913" ); ?> value="913">Нюрба</option>
	<option <?php selected( $ld_city, "914" ); ?> value="914">Олекминск</option>
	<option <?php selected( $ld_city, "915" ); ?> value="915">Олекминск</option>
	<option <?php selected( $ld_city, "916" ); ?> value="916">Покровск</option>
	<option <?php selected( $ld_city, "917" ); ?> value="917">Среднеколымск</option>
	<option <?php selected( $ld_city, "918" ); ?> value="918">Томмот</option>
	<option <?php selected( $ld_city, "919" ); ?> value="919">Удачный</option>
	<option <?php selected( $ld_city, "920" ); ?> value="920">Якутск</option>
	<option <?php selected( $ld_city, "921" ); ?> value="921">Республика Северная Осетия - Алания</option>
	<option <?php selected( $ld_city, "922" ); ?> value="922">Алагир</option>
	<option <?php selected( $ld_city, "923" ); ?> value="923">Ардон</option>
	<option <?php selected( $ld_city, "924" ); ?> value="924">Беслан</option>
	<option <?php selected( $ld_city, "925" ); ?> value="925">Владикавказ</option>
	<option <?php selected( $ld_city, "926" ); ?> value="926">Дигора</option>
	<option <?php selected( $ld_city, "927" ); ?> value="927">Моздок</option>
	<option <?php selected( $ld_city, "928" ); ?> value="928">Республика Татарстан</option>
	<option <?php selected( $ld_city, "929" ); ?> value="929">Агрыз</option>
	<option <?php selected( $ld_city, "930" ); ?> value="930">Азнакаево</option>
	<option <?php selected( $ld_city, "931" ); ?> value="931">Альметьевск</option>
	<option <?php selected( $ld_city, "932" ); ?> value="932">Арск</option>
	<option <?php selected( $ld_city, "933" ); ?> value="933">Бавлы</option>
	<option <?php selected( $ld_city, "934" ); ?> value="934">Болгар</option>
	<option <?php selected( $ld_city, "935" ); ?> value="935">Бугульма</option>
	<option <?php selected( $ld_city, "936" ); ?> value="936">Буинск</option>
	<option <?php selected( $ld_city, "937" ); ?> value="937">Елабуга</option>
	<option <?php selected( $ld_city, "938" ); ?> value="938">Заинск</option>
	<option <?php selected( $ld_city, "939" ); ?> value="939">Зеленодольск</option>
	<option <?php selected( $ld_city, "940" ); ?> value="940">Казань</option>
	<option <?php selected( $ld_city, "941" ); ?> value="941">Лаишево</option>
	<option <?php selected( $ld_city, "942" ); ?> value="942">Лениногорск</option>
	<option <?php selected( $ld_city, "943" ); ?> value="943">Мамадыш</option>
	<option <?php selected( $ld_city, "944" ); ?> value="944">Менделеевск</option>
	<option <?php selected( $ld_city, "945" ); ?> value="945">Мензелинск</option>
	<option <?php selected( $ld_city, "946" ); ?> value="946">Набережные Челны</option>
	<option <?php selected( $ld_city, "947" ); ?> value="947">Нижнекамск</option>
	<option <?php selected( $ld_city, "948" ); ?> value="948">Нурлат</option>
	<option <?php selected( $ld_city, "949" ); ?> value="949">Тетюши</option>
	<option <?php selected( $ld_city, "950" ); ?> value="950">Чистополь</option>
	<option <?php selected( $ld_city, "951" ); ?> value="951">Республика Тыва</option>
	<option <?php selected( $ld_city, "952" ); ?> value="952">Ак-Довурак</option>
	<option <?php selected( $ld_city, "953" ); ?> value="953">Кызыл</option>
	<option <?php selected( $ld_city, "954" ); ?> value="954">Туран</option>
	<option <?php selected( $ld_city, "955" ); ?> value="955">Чадан</option>
	<option <?php selected( $ld_city, "956" ); ?> value="956">Шагонар</option>
	<option <?php selected( $ld_city, "957" ); ?> value="957">Республика Хакасия</option>
	<option <?php selected( $ld_city, "958" ); ?> value="958">Абаза</option>
	<option <?php selected( $ld_city, "959" ); ?> value="959">Абакан</option>
	<option <?php selected( $ld_city, "960" ); ?> value="960">Саяногорск</option>
	<option <?php selected( $ld_city, "961" ); ?> value="961">Сорск</option>
	<option <?php selected( $ld_city, "962" ); ?> value="962">Черногорск</option>
	<option <?php selected( $ld_city, "963" ); ?> value="963">Рязанская область</option>
	<option <?php selected( $ld_city, "964" ); ?> value="964">Касимов</option>
	<option <?php selected( $ld_city, "965" ); ?> value="965">Кораблино</option>
	<option <?php selected( $ld_city, "966" ); ?> value="966">Михайлов</option>
	<option <?php selected( $ld_city, "967" ); ?> value="967">Новомичуринск</option>
	<option <?php selected( $ld_city, "968" ); ?> value="968">Рыбное</option>
	<option <?php selected( $ld_city, "969" ); ?> value="969">Ряжск</option>
	<option <?php selected( $ld_city, "970" ); ?> value="970">Рязань</option>
	<option <?php selected( $ld_city, "971" ); ?> value="971">Сасово</option>
	<option <?php selected( $ld_city, "972" ); ?> value="972">Скопин</option>
	<option <?php selected( $ld_city, "973" ); ?> value="973">Спас-Клепики</option>
	<option <?php selected( $ld_city, "974" ); ?> value="974">Спасск-Рязанский</option>
	<option <?php selected( $ld_city, "975" ); ?> value="975">Шацк</option>
	<option <?php selected( $ld_city, "976" ); ?> value="976">Саратовская область</option>
	<option <?php selected( $ld_city, "977" ); ?> value="977">Аркадак</option>
	<option <?php selected( $ld_city, "978" ); ?> value="978">Аткарск</option>
	<option <?php selected( $ld_city, "979" ); ?> value="979">Балаково</option>
	<option <?php selected( $ld_city, "980" ); ?> value="980">Балашов</option>
	<option <?php selected( $ld_city, "981" ); ?> value="981">Вольск</option>
	<option <?php selected( $ld_city, "982" ); ?> value="982">Вольск-18</option>
	<option <?php selected( $ld_city, "983" ); ?> value="983">Ершов</option>
	<option <?php selected( $ld_city, "984" ); ?> value="984">Калининск</option>
	<option <?php selected( $ld_city, "985" ); ?> value="985">Красноармейск</option>
	<option <?php selected( $ld_city, "986" ); ?> value="986">Красный Кут</option>
	<option <?php selected( $ld_city, "987" ); ?> value="987">Маркс</option>
	<option <?php selected( $ld_city, "988" ); ?> value="988">Новоузенск</option>
	<option <?php selected( $ld_city, "989" ); ?> value="989">Петровск</option>
	<option <?php selected( $ld_city, "990" ); ?> value="990">Пугачев</option>
	<option <?php selected( $ld_city, "991" ); ?> value="991">Ртищево</option>
	<option <?php selected( $ld_city, "992" ); ?> value="992">Саратов</option>
	<option <?php selected( $ld_city, "993" ); ?> value="993">Хвалынск</option>
	<option <?php selected( $ld_city, "994" ); ?> value="994">Шиханы</option>
	<option <?php selected( $ld_city, "995" ); ?> value="995">Энгельс</option>
	<option <?php selected( $ld_city, "996" ); ?> value="996">Энгельс-19</option>
	<option <?php selected( $ld_city, "997" ); ?> value="997">Энгельс-2</option>
	<option <?php selected( $ld_city, "998" ); ?> value="998">Сахалинская область</option>
	<option <?php selected( $ld_city, "999" ); ?> value="999">Александровск-Сахалинский</option>
	<option <?php selected( $ld_city, "1000" ); ?> value="1000">Анива</option>
	<option <?php selected( $ld_city, "1001" ); ?> value="1001">Горнозаводск</option>
	<option <?php selected( $ld_city, "1002" ); ?> value="1002">Долинск</option>
	<option <?php selected( $ld_city, "1003" ); ?> value="1003">Корсаков</option>
	<option <?php selected( $ld_city, "1004" ); ?> value="1004">Курильск</option>
	<option <?php selected( $ld_city, "1005" ); ?> value="1005">Макаров</option>
	<option <?php selected( $ld_city, "1006" ); ?> value="1006">Невельск</option>
	<option <?php selected( $ld_city, "1007" ); ?> value="1007">Оха</option>
	<option <?php selected( $ld_city, "1008" ); ?> value="1008">Поронайск</option>
	<option <?php selected( $ld_city, "1009" ); ?> value="1009">Северо-Курильск</option>
	<option <?php selected( $ld_city, "1010" ); ?> value="1010">Томари</option>
	<option <?php selected( $ld_city, "1011" ); ?> value="1011">Углегорск</option>
	<option <?php selected( $ld_city, "1012" ); ?> value="1012">Холмск</option>
	<option <?php selected( $ld_city, "1013" ); ?> value="1013">Шахтерск</option>
	<option <?php selected( $ld_city, "1014" ); ?> value="1014">Южно-Сахалинск</option>
	<option <?php selected( $ld_city, "1015" ); ?> value="1015">Смоленская область</option>
	<option <?php selected( $ld_city, "1016" ); ?> value="1016">Велиж</option>
	<option <?php selected( $ld_city, "1017" ); ?> value="1017">Вязьма</option>
	<option <?php selected( $ld_city, "1018" ); ?> value="1018">Гагарин</option>
	<option <?php selected( $ld_city, "1019" ); ?> value="1019">Демидов</option>
	<option <?php selected( $ld_city, "1020" ); ?> value="1020">Десногорск</option>
	<option <?php selected( $ld_city, "1021" ); ?> value="1021">Дорогобуж</option>
	<option <?php selected( $ld_city, "1022" ); ?> value="1022">Духовщина</option>
	<option <?php selected( $ld_city, "1023" ); ?> value="1023">Ельня</option>
	<option <?php selected( $ld_city, "1024" ); ?> value="1024">Починок</option>
	<option <?php selected( $ld_city, "1025" ); ?> value="1025">Рославль</option>
	<option <?php selected( $ld_city, "1026" ); ?> value="1026">Рудня</option>
	<option <?php selected( $ld_city, "1027" ); ?> value="1027">Сафоново</option>
	<option <?php selected( $ld_city, "1028" ); ?> value="1028">Смоленск</option>
	<option <?php selected( $ld_city, "1029" ); ?> value="1029">Сычевка</option>
	<option <?php selected( $ld_city, "1030" ); ?> value="1030">Ярцево</option>
	<option <?php selected( $ld_city, "1031" ); ?> value="1031">Ставропольский край</option>
	<option <?php selected( $ld_city, "1032" ); ?> value="1032">Благодарный</option>
	<option <?php selected( $ld_city, "1033" ); ?> value="1033">Буденновск</option>
	<option <?php selected( $ld_city, "1034" ); ?> value="1034">Георгиевск</option>
	<option <?php selected( $ld_city, "1035" ); ?> value="1035">Ессентуки</option>
	<option <?php selected( $ld_city, "1036" ); ?> value="1036">Железноводск</option>
	<option <?php selected( $ld_city, "1037" ); ?> value="1037">Зеленокумск</option>
	<option <?php selected( $ld_city, "1038" ); ?> value="1038">Изобильный</option>
	<option <?php selected( $ld_city, "1039" ); ?> value="1039">Ипатово</option>
	<option <?php selected( $ld_city, "1040" ); ?> value="1040">Кисловодск</option>
	<option <?php selected( $ld_city, "1041" ); ?> value="1041">Лермонтов</option>
	<option <?php selected( $ld_city, "1042" ); ?> value="1042">Минеральные Воды</option>
	<option <?php selected( $ld_city, "1043" ); ?> value="1043">Михайловск</option>
	<option <?php selected( $ld_city, "1044" ); ?> value="1044">Невинномысск</option>
	<option <?php selected( $ld_city, "1045" ); ?> value="1045">Нефтекумск</option>
	<option <?php selected( $ld_city, "1046" ); ?> value="1046">Новоалександровск</option>
	<option <?php selected( $ld_city, "1047" ); ?> value="1047">Новопавловск</option>
	<option <?php selected( $ld_city, "1048" ); ?> value="1048">Пятигорск</option>
	<option <?php selected( $ld_city, "1049" ); ?> value="1049">Светлоград</option>
	<option <?php selected( $ld_city, "1050" ); ?> value="1050">Ставрополь</option>
	<option <?php selected( $ld_city, "1051" ); ?> value="1051">Тамбовская область</option>
	<option <?php selected( $ld_city, "1052" ); ?> value="1052">Жердевка</option>
	<option <?php selected( $ld_city, "1053" ); ?> value="1053">Кирсанов</option>
	<option <?php selected( $ld_city, "1054" ); ?> value="1054">Котовск</option>
	<option <?php selected( $ld_city, "1055" ); ?> value="1055">Мичуринск</option>
	<option <?php selected( $ld_city, "1056" ); ?> value="1056">Моршанск</option>
	<option <?php selected( $ld_city, "1057" ); ?> value="1057">Рассказово</option>
	<option <?php selected( $ld_city, "1058" ); ?> value="1058">Тамбов</option>
	<option <?php selected( $ld_city, "1059" ); ?> value="1059">Уварово</option>
	<option <?php selected( $ld_city, "1060" ); ?> value="1060">Тверская область</option>
	<option <?php selected( $ld_city, "1061" ); ?> value="1061">Андреаполь</option>
	<option <?php selected( $ld_city, "1062" ); ?> value="1062">Бежецк</option>
	<option <?php selected( $ld_city, "1063" ); ?> value="1063">Белый</option>
	<option <?php selected( $ld_city, "1064" ); ?> value="1064">Бологое</option>
	<option <?php selected( $ld_city, "1065" ); ?> value="1065">Весьегонск</option>
	<option <?php selected( $ld_city, "1066" ); ?> value="1066">Вышний Волочек</option>
	<option <?php selected( $ld_city, "1067" ); ?> value="1067">Западная Двина</option>
	<option <?php selected( $ld_city, "1068" ); ?> value="1068">Зубцов</option>
	<option <?php selected( $ld_city, "1069" ); ?> value="1069">Калязин</option>
	<option <?php selected( $ld_city, "1070" ); ?> value="1070">Кашин</option>
	<option <?php selected( $ld_city, "1071" ); ?> value="1071">Кимры</option>
	<option <?php selected( $ld_city, "1072" ); ?> value="1072">Конаково</option>
	<option <?php selected( $ld_city, "1073" ); ?> value="1073">Красный Холм</option>
	<option <?php selected( $ld_city, "1074" ); ?> value="1074">Кувшиново</option>
	<option <?php selected( $ld_city, "1075" ); ?> value="1075">Лихославль</option>
	<option <?php selected( $ld_city, "1076" ); ?> value="1076">Нелидово</option>
	<option <?php selected( $ld_city, "1077" ); ?> value="1077">Осташков</option>
	<option <?php selected( $ld_city, "1078" ); ?> value="1078">Ржев</option>
	<option <?php selected( $ld_city, "1079" ); ?> value="1079">Старица</option>
	<option <?php selected( $ld_city, "1080" ); ?> value="1080">Тверь</option>
	<option <?php selected( $ld_city, "1081" ); ?> value="1081">Торжок</option>
	<option <?php selected( $ld_city, "1082" ); ?> value="1082">Торопец</option>
	<option <?php selected( $ld_city, "1083" ); ?> value="1083">Удомля</option>
	<option <?php selected( $ld_city, "1084" ); ?> value="1084">Томская область</option>
	<option <?php selected( $ld_city, "1085" ); ?> value="1085">Асино</option>
	<option <?php selected( $ld_city, "1086" ); ?> value="1086">Кедровый</option>
	<option <?php selected( $ld_city, "1087" ); ?> value="1087">Колпашево</option>
	<option <?php selected( $ld_city, "1088" ); ?> value="1088">Северск</option>
	<option <?php selected( $ld_city, "1089" ); ?> value="1089">Стрежевой</option>
	<option <?php selected( $ld_city, "1090" ); ?> value="1090">Томск</option>
	<option <?php selected( $ld_city, "1091" ); ?> value="1091">Тульская область</option>
	<option <?php selected( $ld_city, "1092" ); ?> value="1092">Алексин</option>
	<option <?php selected( $ld_city, "1093" ); ?> value="1093">Белев</option>
	<option <?php selected( $ld_city, "1094" ); ?> value="1094">Богородицк</option>
	<option <?php selected( $ld_city, "1095" ); ?> value="1095">Болохово</option>
	<option <?php selected( $ld_city, "1096" ); ?> value="1096">Венев</option>
	<option <?php selected( $ld_city, "1097" ); ?> value="1097">Донской</option>
	<option <?php selected( $ld_city, "1098" ); ?> value="1098">Ефремов</option>
	<option <?php selected( $ld_city, "1099" ); ?> value="1099">Кимовск</option>
	<option <?php selected( $ld_city, "1100" ); ?> value="1100">Киреевск</option>
	<option <?php selected( $ld_city, "1101" ); ?> value="1101">Липки</option>
	<option <?php selected( $ld_city, "1102" ); ?> value="1102">Новомосковск</option>
	<option <?php selected( $ld_city, "1103" ); ?> value="1103">Плавск</option>
	<option <?php selected( $ld_city, "1104" ); ?> value="1104">Советск</option>
	<option <?php selected( $ld_city, "1105" ); ?> value="1105">Сокольники</option>
	<option <?php selected( $ld_city, "1106" ); ?> value="1106">Суворов</option>
	<option <?php selected( $ld_city, "1107" ); ?> value="1107">Тула</option>
	<option <?php selected( $ld_city, "1108" ); ?> value="1108">Узловая</option>
	<option <?php selected( $ld_city, "1109" ); ?> value="1109">Чекалин</option>
	<option <?php selected( $ld_city, "1110" ); ?> value="1110">Щекино</option>
	<option <?php selected( $ld_city, "1111" ); ?> value="1111">Ясногорск</option>
	<option <?php selected( $ld_city, "1112" ); ?> value="1112">Тюменская область</option>
	<option <?php selected( $ld_city, "1113" ); ?> value="1113">Заводоуковск</option>
	<option <?php selected( $ld_city, "1114" ); ?> value="1114">Ишим</option>
	<option <?php selected( $ld_city, "1115" ); ?> value="1115">Тобольск</option>
	<option <?php selected( $ld_city, "1116" ); ?> value="1116">Тюмень</option>
	<option <?php selected( $ld_city, "1117" ); ?> value="1117">Ялуторовск</option>
	<option <?php selected( $ld_city, "1118" ); ?> value="1118">Удмуртская республика</option>
	<option <?php selected( $ld_city, "1119" ); ?> value="1119">Воткинск</option>
	<option <?php selected( $ld_city, "1120" ); ?> value="1120">Глазов</option>
	<option <?php selected( $ld_city, "1121" ); ?> value="1121">Ижевск</option>
	<option <?php selected( $ld_city, "1122" ); ?> value="1122">Камбарка</option>
	<option <?php selected( $ld_city, "1123" ); ?> value="1123">Можга</option>
	<option <?php selected( $ld_city, "1124" ); ?> value="1124">Сарапул</option>
	<option <?php selected( $ld_city, "1125" ); ?> value="1125">Ульяновская область</option>
	<option <?php selected( $ld_city, "1126" ); ?> value="1126">Барыш</option>
	<option <?php selected( $ld_city, "1127" ); ?> value="1127">Димитровград</option>
	<option <?php selected( $ld_city, "1128" ); ?> value="1128">Инза</option>
	<option <?php selected( $ld_city, "1129" ); ?> value="1129">Новоульяновск</option>
	<option <?php selected( $ld_city, "1130" ); ?> value="1130">Сенгилей</option>
	<option <?php selected( $ld_city, "1131" ); ?> value="1131">Ульяновск</option>
	<option <?php selected( $ld_city, "1132" ); ?> value="1132">Хабаровский край</option>
	<option <?php selected( $ld_city, "1133" ); ?> value="1133">Амурск</option>
	<option <?php selected( $ld_city, "1134" ); ?> value="1134">Бикин</option>
	<option <?php selected( $ld_city, "1135" ); ?> value="1135">Вяземский</option>
	<option <?php selected( $ld_city, "1136" ); ?> value="1136">Комсомольск-на-Амуре</option>
	<option <?php selected( $ld_city, "1137" ); ?> value="1137">Николаевск-на-Амуре</option>
	<option <?php selected( $ld_city, "1138" ); ?> value="1138">Советская Гавань</option>
	<option <?php selected( $ld_city, "1139" ); ?> value="1139">Хабаровск</option>
	<option <?php selected( $ld_city, "1140" ); ?> value="1140">Ханты-Мансийский автономный округ</option>
	<option <?php selected( $ld_city, "1141" ); ?> value="1141">Белоярский</option>
	<option <?php selected( $ld_city, "1142" ); ?> value="1142">Когалым</option>
	<option <?php selected( $ld_city, "1143" ); ?> value="1143">Лангепас</option>
	<option <?php selected( $ld_city, "1144" ); ?> value="1144">Лянтор</option>
	<option <?php selected( $ld_city, "1145" ); ?> value="1145">Мегион</option>
	<option <?php selected( $ld_city, "1146" ); ?> value="1146">Нефтеюганск</option>
	<option <?php selected( $ld_city, "1147" ); ?> value="1147">Нижневартовск</option>
	<option <?php selected( $ld_city, "1148" ); ?> value="1148">Нягань</option>
	<option <?php selected( $ld_city, "1149" ); ?> value="1149">Покачи</option>
	<option <?php selected( $ld_city, "1150" ); ?> value="1150">Пыть-Ях</option>
	<option <?php selected( $ld_city, "1151" ); ?> value="1151">Радужный</option>
	<option <?php selected( $ld_city, "1152" ); ?> value="1152">Советский</option>
	<option <?php selected( $ld_city, "1153" ); ?> value="1153">Сургут</option>
	<option <?php selected( $ld_city, "1154" ); ?> value="1154">Урай</option>
	<option <?php selected( $ld_city, "1155" ); ?> value="1155">Ханты-Мансийск</option>
	<option <?php selected( $ld_city, "1156" ); ?> value="1156">Югорск</option>
	<option <?php selected( $ld_city, "1157" ); ?> value="1157">Челябинская область</option>
	<option <?php selected( $ld_city, "1158" ); ?> value="1158">Аша</option>
	<option <?php selected( $ld_city, "1159" ); ?> value="1159">Бакал</option>
	<option <?php selected( $ld_city, "1160" ); ?> value="1160">Верхнеуральск</option>
	<option <?php selected( $ld_city, "1161" ); ?> value="1161">Верхний Уфалей</option>
	<option <?php selected( $ld_city, "1162" ); ?> value="1162">Еманжелинск</option>
	<option <?php selected( $ld_city, "1163" ); ?> value="1163">Златоуст</option>
	<option <?php selected( $ld_city, "1164" ); ?> value="1164">Карабаш</option>
	<option <?php selected( $ld_city, "1165" ); ?> value="1165">Карталы</option>
	<option <?php selected( $ld_city, "1166" ); ?> value="1166">Касли</option>
	<option <?php selected( $ld_city, "1167" ); ?> value="1167">Катав-Ивановск</option>
	<option <?php selected( $ld_city, "1168" ); ?> value="1168">Копейск</option>
	<option <?php selected( $ld_city, "1169" ); ?> value="1169">Коркино</option>
	<option <?php selected( $ld_city, "1170" ); ?> value="1170">Куса</option>
	<option <?php selected( $ld_city, "1171" ); ?> value="1171">Кыштым</option>
	<option <?php selected( $ld_city, "1172" ); ?> value="1172">Магнитогорск</option>
	<option <?php selected( $ld_city, "1173" ); ?> value="1173">Миасс</option>
	<option <?php selected( $ld_city, "1174" ); ?> value="1174">Миньяр</option>
	<option <?php selected( $ld_city, "1175" ); ?> value="1175">Нязепетровск</option>
	<option <?php selected( $ld_city, "1176" ); ?> value="1176">Озерск</option>
	<option <?php selected( $ld_city, "1177" ); ?> value="1177">Пласт</option>
	<option <?php selected( $ld_city, "1178" ); ?> value="1178">Сатка</option>
	<option <?php selected( $ld_city, "1179" ); ?> value="1179">Сим</option>
	<option <?php selected( $ld_city, "1180" ); ?> value="1180">Снежинск</option>
	<option <?php selected( $ld_city, "1181" ); ?> value="1181">Трехгорный</option>
	<option <?php selected( $ld_city, "1182" ); ?> value="1182">Трехгорный-1</option>
	<option <?php selected( $ld_city, "1183" ); ?> value="1183">Троицк</option>
	<option <?php selected( $ld_city, "1184" ); ?> value="1184">Усть-Катав</option>
	<option <?php selected( $ld_city, "1185" ); ?> value="1185">Чебаркуль</option>
	<option <?php selected( $ld_city, "1186" ); ?> value="1186">Челябинск</option>
	<option <?php selected( $ld_city, "1187" ); ?> value="1187">Южноуральск</option>
	<option <?php selected( $ld_city, "1188" ); ?> value="1188">Юрюзань</option>
	<option <?php selected( $ld_city, "1189" ); ?> value="1189">Чеченская республика</option>
	<option <?php selected( $ld_city, "1190" ); ?> value="1190">Аргун</option>
	<option <?php selected( $ld_city, "1191" ); ?> value="1191">Грозный</option>
	<option <?php selected( $ld_city, "1192" ); ?> value="1192">Гудермес</option>
	<option <?php selected( $ld_city, "1193" ); ?> value="1193">Урус-Мартан</option>
	<option <?php selected( $ld_city, "1194" ); ?> value="1194">Шали</option>
	<option <?php selected( $ld_city, "1195" ); ?> value="1195">Чувашcкая республика</option>
	<option <?php selected( $ld_city, "1196" ); ?> value="1196">Алатырь</option>
	<option <?php selected( $ld_city, "1197" ); ?> value="1197">Канаш</option>
	<option <?php selected( $ld_city, "1198" ); ?> value="1198">Козловка</option>
	<option <?php selected( $ld_city, "1199" ); ?> value="1199">Мариинский Посад</option>
	<option <?php selected( $ld_city, "1200" ); ?> value="1200">Новочебоксарск</option>
	<option <?php selected( $ld_city, "1201" ); ?> value="1201">Цивильск</option>
	<option <?php selected( $ld_city, "1202" ); ?> value="1202">Чебоксары</option>
	<option <?php selected( $ld_city, "1203" ); ?> value="1203">Шумерля</option>
	<option <?php selected( $ld_city, "1204" ); ?> value="1204">Ядрин</option>
	<option <?php selected( $ld_city, "1205" ); ?> value="1205">Чукотский автономный округ</option>
	<option <?php selected( $ld_city, "1206" ); ?> value="1206">Анадырь</option>
	<option <?php selected( $ld_city, "1207" ); ?> value="1207">Билибино</option>
	<option <?php selected( $ld_city, "1208" ); ?> value="1208">Певек</option>
	<option <?php selected( $ld_city, "1209" ); ?> value="1209">Ямало-Ненецкий автономный округ</option>
	<option <?php selected( $ld_city, "1210" ); ?> value="1210">Губкинский</option>
	<option <?php selected( $ld_city, "1211" ); ?> value="1211">Лабытнанги</option>
	<option <?php selected( $ld_city, "1212" ); ?> value="1212">Муравленко</option>
	<option <?php selected( $ld_city, "1213" ); ?> value="1213">Надым</option>
	<option <?php selected( $ld_city, "1214" ); ?> value="1214">Новый Уренгой</option>
	<option <?php selected( $ld_city, "1215" ); ?> value="1215">Ноябрьск</option>
	<option <?php selected( $ld_city, "1216" ); ?> value="1216">Салехард</option>
	<option <?php selected( $ld_city, "1217" ); ?> value="1217">Тарко-Сале</option>
	<option <?php selected( $ld_city, "1218" ); ?> value="1218">Ярославская область</option>
	<option <?php selected( $ld_city, "1219" ); ?> value="1219">Гаврилов-Ям</option>
	<option <?php selected( $ld_city, "1220" ); ?> value="1220">Данилов</option>
	<option <?php selected( $ld_city, "1221" ); ?> value="1221">Любим</option>
	<option <?php selected( $ld_city, "1222" ); ?> value="1222">Мышкин</option>
	<option <?php selected( $ld_city, "1223" ); ?> value="1223">Переславль-Залесский</option>
	<option <?php selected( $ld_city, "1224" ); ?> value="1224">Пошехонье</option>
	<option <?php selected( $ld_city, "1225" ); ?> value="1225">Ростов</option>
	<option <?php selected( $ld_city, "1226" ); ?> value="1226">Рыбинск</option>
	<option <?php selected( $ld_city, "1227" ); ?> value="1227">Тутаев</option>
	<option <?php selected( $ld_city, "1228" ); ?> value="1228">Углич</option>
	<option <?php selected( $ld_city, "1229" ); ?> value="1229">Ярославль</option>
</select>

<?php
}
?>
